### ISSUE TITLE
Upcoming Azure Batch node agent changes to CloudServiceConfiguration based pools

### ISSUE THREAD

**Issue by matthchr** [Azure/Batch#1]
### What is the node agent?
The Node Agent is the part of the Azure Batch service that runs on the compute nodes in a Batch pool. The Node Agent downloads resource files and application packages as part of executing Azure Batch tasks. The Node Agent also launches and monitors task command lines. When a task completes, 
the Node Agent updates the Azure Batch service with any errors that were encountered during the execution of the task, as well as the task exit code if applicable.

### What is the change?
There are currently two node agents, one that runs on `CloudServiceConfiguration` pool nodes and one that runs on both Windows and Linux `VirtualMachineConfiguration` pool nodes. We are moving to one common agent, with the current `CloudServiceConfiguration` agent being replaced with the `VirtualMachineConfiguration` agent.

### Will there be any impact to `CloudServiceConfiguration` pools?
There should be no impact.  The common node agent has been in production for several years running on `VirtualMachineConfiguration` pool nodes and we have been testing it extensively on `CloudServiceConfiguration` pool nodes with early adopters.

### What are the feature differences between pool configuration types?
There are features that are currently only available to `VirtualMachineConfiguration` pools that will become available to `CloudServiceConfiguration` pools.  For example, output file upload and node agent log upload.  In addition, the number of task interruptions due to occasional underlying VM upgrades will be reduced (VM guest agent updates will no longer cause the interruption of a running task). Moreover, since there is only one agent to target (instead of 2 like we had in the past) future features should be delivered at parity (whenever technically possible) between the pool configuration types.

### How can I tell if my pool is using the old agent or the new one?
In general, you shouldn't need to know, but the old agent had a process called “TVM.exe”, whereas new agents will be running a process called “node_agent.exe”

### When is this happening?
We are planning a phased rollout starting May 1st 2018; the rollout will be gradual and there is no guarantee that your account will be switched to use the new agent on May 1st, but it may happen any time after that. If you wish to try the new agent out ahead of time you can submit a request to try the common agent by contacting customer support, supplying your Batch account name and region.

#### Issue with Windows LocalMachine certificates
If you are adding certificate references on your pool which install into the Windows LocalMachine certificate store, and are running tasks without admin access which need access to the certificate's private key, your tasks will work on the old agent but not work in the new agent. This is because the old agent adds an ACL to allow access to the private key the LocalMachine certificate by task users, which is different than the default Windows behavior of allowing access LocalMachine certificate private keys only for admin users. For security reasons, we decided not to keep this behavior in the new agent. In the cases where this has come up so far, the solution was for the customer to move the certificate from the LocalMachine certificate store to the CurrentUser certificate store, which allows access to the private keys by non-admin users by default in Windows.

Note: If you are installing certificates into "Root" and are running your tasks as non-admin users, you will need to leave the "Root" certificates in the LocalMachine store. Another way to say this is that if you are installing cer files, those can stay in LocalMachine as they don't have a private key. Only pfx files where your non-admin task needs access to the private key should be moved to "My" in CurrentUser

#### Issue with change in stdin redirection on Windows
The new agent correctly redirects stdin to your task process. This is in contrast to the old agent which supplied an invalid handle for stdin. In most cases this isn't noticeable. In some cases, applications expect a valid stdin handle and didn't work correctly in the old agent because of the invalid handle supplied. If your task attempts to read from stdin and was previously swallowing any errors from doing so, it's possible with this change you observe your tasks get "stuck" waiting for stdin data that will never come. Make sure that you provide stdin data if your application expects it, Azure Batch currently does not provide any stdin data on your behalf.

### How can I opt in to getting the updated agent?
You can contact us by [filing a ticket through the Azure portal](https://ms.portal.azure.com/#create/Microsoft.Support). Specify the Batch account you would like to pilot the new agent on, and if asked to specify a "problem type" choose "configuration and setup issues." In the ticket itself, mention that you would like to pilot the new agent for `CloudServiceConfiguration` pools.

**Comment by MatthewSteeples** [comment]
How "gradual" are you expecting this roll out to be? I've just checked and we're still running the old agent

**Comment by matthchr** [comment]
@MatthewSteeples - it's actually already rolled out but you need to create a new pool to get it. If you just don't create pools often/ever then you may still be on the old agent (which is fine provided things are working for you -- we aren't force migrating people just letting them move naturally if/when they create new pools).

If you have any questions and/or think you should have the new agent but don't on a fresh pool, you can open a support ticket with the details and we can look into it, or you can tell me your Batch Account name and pool name here provided they aren't sensitive information you don't want shared publicly and I can investigate.

**Comment by MatthewSteeples** [comment]
@matthchr That makes sense. Our pools are quite long living. I assumed it was a VM image-based thing rather than a pool-based thing.

We'll be re-creating our pools once Server 2019 (family 6) becomes available as an option (Although we don't seem to be able to pick the version when creating the pool anymore)
