### ISSUE TITLE
Output Files from Batch Task to Azure Blob Storage - be able to set content-encoding headers?

### ISSUE THREAD

**Issue by jis260** [Azure/Batch#102]
#### Feature Request Description
- I have Azure Batch Tasks that create many files and these are uploaded to Azure Blob storage.
- I'm using the output_files TaskAddParameter to copy these from the node to Azure storage. I was hoping that the [OutputFile ](https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.models.outputfile?view=azure-python) constructor let you set blob headers like content-encoding. I can't see any documentation of this?

#### Describe Preferred Solution
Make it possible to set common blob properties for output files from an Azure Batch Task.

#### Describe Alternatives Considered
Running this as a subsequent task that sets the content-encoding.
Thought about a CDN re-write rule, because the blob outputs will be served via CDN, but it is not possible to override the content-encoding header as per the [documentation](https://docs.vdms.com/cdn/Content/HRE/F/Modify-Client-Response-Header.html)

**Comment by kthy** [comment]
Very much related, it would be very convenient to be able to set the `metadata` and `tags` values for output files in `TaskAddParameter`.

**Comment by staer** [comment]
The ability to set arbitrary headers for file upload (content-type, metadata, tags, etc.) is a planned feature though I can't commit when it will land in public Batch. I will update this thread when I have more information.

**Comment by staer** [comment]
Sorry for the delay in replying here, this feature is now live. You can specify any header key/value pair when defining output files whose destination is Azure Storage.

REST docs: https://docs.microsoft.com/en-us/rest/api/batchservice/task/add#outputfileblobcontainerdestination

C#/Python/etc. APIs should also be updated as well.

Happy coding!
