### ISSUE TITLE
List supported images lists images which don't actually work

### ISSUE THREAD

**Issue by lesterlitch** [Azure/Batch#103]
#### Problem Description

Images in list_supported_images don't actually work when trying to create new nodes.

#### Steps to Reproduce

List supported images in azure batch, i.e. in python:

batch_client.account.list_supported_images()

attempt to create a pool using the listed image, such as:

 {'node_agent_sku_id': 'batch.node.centos 7',
  'image_reference': {'publisher': 'microsoft-azure-batch',
   'offer': 'centos-container',
   'sku': '7-4',
   'version': 'latest'},
  'os_type': 'linux',
  'capabilities': ['DockerCompatible',
   'NvidiaTeslaDriverInstalled',
   'NvidiaGridDriverInstalled'],
  'verification_type': 'unverified'}, 

#### Expected Results

Node starts

#### Actual Results

Code: AllocationFailed

Message:
Desired number of dedicated nodes could not be allocated

Values:
Reason - The specified image is not found

#### Additonal Comments

The web portal only shows a tiny subset of images listed returned by list_supported_images in the available drop down menus.

**Comment by alfpark** [comment]
Portal only displays `verified` images. This image is listed as `unverified` and may stop working when removed from the Marketplace.

**Comment by lesterlitch** [comment]
I don't know if it's just me, but don't you think a method called "list supported images" should... list only supported images that exist? Can you not tell which images are live on the marketplace?
