### ISSUE TITLE
EventGrid Integration

### ISSUE THREAD

**Issue by christophwille** [Azure/Batch#104]
I want to be notified when the status of a Task (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.common.taskstate?view=azure-dotnet) changes.

Reason: I don't want to have to do permanent polling on status, but be notified instead to save resources. (today I notify via EventGrid on drop of output files, but sometimes a job can fail with no output files or I want the info "is being processed right now" to be visible for users without polling like every second).

**Comment by alfpark** [comment]
You can integrate with diagnostics service event logs with events being sent to endpoints of your choosing: https://learn.microsoft.com/azure/batch/batch-diagnostics
