### ISSUE TITLE
RDMA-enabled node with Container task ends in failure

### ISSUE THREAD

**Issue by martinjoshua** [Azure/Batch#110]
#### Problem Description

An odd error is returned when attempting to start a docker container task on the standard_hb120rs_v2 RDMA-enabled nodes.

#### Steps to Reproduce

The following code should create a pool with 1 standard_hb120rs_v2, using the centos-container-rdma 7-7 image. It then loads a docker image from ACR and executes 6 tasks using that image and it's default ENTRYPOINT, but all end in failure.

```
            var poolId = "testPool";
            var jobId = "testJob";
            var job = batchClient.JobOperations.CreateJob();
            job.Id = jobId;
            job.PoolInformation = new PoolInformation { PoolId = poolId };
            job.UsesTaskDependencies = true;
            job.OnAllTasksComplete = OnAllTasksComplete.NoAction;

            job.Commit();

        
            var images = batchClient
                .PoolOperations
                .ListSupportedImages(detailLevel: new ODATADetailLevel(filterClause: "verificationType eq 'verified'"));

            var offers = images.Where(a => a.ImageReference.Publisher == "microsoft-azure-batch"
                && a.ImageReference.Offer == "centos-container-rdma" && a.ImageReference.Sku == "7-7")
                .ToList();

                var image = offers.LastOrDefault();

                var vmConfiguration = new VirtualMachineConfiguration(
                    imageReference: image.ImageReference,
                    nodeAgentSkuId: image.NodeAgentSkuId)
                {
                    ContainerConfiguration = new ContainerConfiguration
                    {
                        ContainerImageNames = new List<string> { "....azurecr.io/image/path" },
                        ContainerRegistries = new List<ContainerRegistry> {
                            new ContainerRegistry(
                                registryServer: ".....azurecr.io",
                                userName: "...",
                                password: "...") 
                        }
                    }
                };

                var pool = batchClient.PoolOperations.CreatePool(
                    poolId: poolId,
                    targetDedicatedComputeNodes: 0,
                    targetLowPriorityComputeNodes: 1,
                    virtualMachineSize: "standard_hb120rs_v2",
                    virtualMachineConfiguration: vmConfiguration);

                pool.MountConfiguration = new List<MountConfiguration> {
                    new MountConfiguration(new AzureBlobFileSystemConfiguration
                    (
                        ...
                    ))
                };
                pool.InterComputeNodeCommunicationEnabled = true;
                pool.TaskSlotsPerNode = 6;
                pool.TaskSchedulingPolicy = new TaskSchedulingPolicy(ComputeNodeFillType.Pack);

                await pool.CommitAsync().ConfigureAwait(false);

                var tasks = Enumerable.Range(1, 6)
                    .Select(i => new CloudTask($"PYTHON{i}", string.Empty) { 
                        RequiredSlots = 1,
                        UserIdentity = new UserIdentity(new AutoUserSpecification(AutoUserScope.Pool, ElevationLevel.Admin)),
                        ContainerSettings = new TaskContainerSettings(
                            "...azurecr.io/image/path",
                            containerRunOptions: "--rm", 
                            workingDirectory: ContainerWorkingDirectory.ContainerImageDefault)                            
                    })
                    .ToList();

                // Add all tasks to the job.  
                batchClient.JobOperations.AddTask(jobId, tasks);
```

#### Expected Results

I would expect the tasks to run to completion

#### Actual Results

Instead, the task immediately fails with a FailureExitCode.  The stderr.txt file contains the following:
`Error response from daemon: error gathering device information while adding custom device "/dev/infiniband/rdma_cm": no such file or directory`

I have logged into the host, and the image is successfully in docker (docker image ls) but no containers were created (docker container ls).  

I can then run `sudo docker run -it --rm ...acr/image/path` and the docker container is created and executed.

On the host, the `/dev/infiniband/rdma_cm` directory does not exit.  But where is this configuration coming from?

I have tried removing "EnableInterNodeCommunication" from the pool creation, removing slots, and different images as well (without `-rdma`), also tried the Ubuntu image from Microsoft, but all result in failure.

I have logged into the host and indeed that directory does not exist.  There doesn't seem to be an issue with the image itself, since I can run it when I remote in to the host.  Is there any issue with the HB120 VM's running Docker?

UPDATE: Running on "standard_h8" presented no problems. It seems to be an issue with the HB120?

**Comment by vincentlabonte** [comment]
Thanks for bringing this issue to our attention. We are investigating and will update this thread as soon as possible.

**Comment by vincentlabonte** [comment]
#### What Happened
After investigation, we determined that our "centos-container-rdma 7-7" image was missing the "/dev/infiniband/rdma_cm" device required to use RDMA. On RDMA-capable VMs, as part of the docker run command, we add all RDMA required devices which, in this case, was missing the "/dev/infiniband/rdma_cm" device .

#### Mitigation
We have updated the image and it now has the required device. You should now be able to use the latest "centos-container-rdma 7-7" image with a container workload on HB-series VMs.

\
Note: The reason why it was running on Standard_H8 and not Standard_HB120rs_v2 is because Standard_H8 is not RDMA-capable.

**Comment by alfpark** [comment]
Thanks @vincentlabonte!

**Comment by martinjoshua** [comment]
Has the updated image been deployed yet? I am still receiving this error; I also just tried with the centos-container-rdma 8.2 image from Azure Batch but received the same message.

**Comment by vincentlabonte** [comment]
The updated images should have been published to the Azure Marketplace. You will have to scale your pool down to zero and back up to make sure it picks up the new "latest" image version.

Also, make sure you are using "centos-container-rdma" and not "centos-container" as the latter will not have the required device. 

Note: "centos-container-rdma" currently does not have a CentOS 8-2 SKU. Please use the 8-1 SKU or the 7-7 SKU.
