### ISSUE TITLE
CloudTask.Constraints is not being picked up

### ISSUE THREAD

**Issue by christophwille** [Azure/Batch#112]
I wanted to set the RetentionTime via CloudTask.Constraints. I tried various approaches such as

```
var t = new CloudTask(...)
{
  Constraints = new TaskConstraint()
  {
    RetentionTime = ...
  }
}
```

or 

```
var taskConstraints = new TaskConstraints();
taskConstraints.RetentionTime = TimeSpan.FromDays(1);
t.Constraints = taskConstraints;
```

before calling into `AddTaskAsync`. Each and every time / variation I end up with the default in the Azure Portal:

![image](https://user-images.githubusercontent.com/344208/127127524-cf43f9de-b035-49b4-8aa4-8bc58240ee76.png)

Is it not picked up because I am doing something wrong, not being picked up because of a bug, or not shown properly in the portal?

**Comment by staer** [comment]
This seems to be working for me, example code:

```
using System;
using Microsoft.Azure.Batch;
using Microsoft.Azure.Batch.Auth;

namespace BatchRetentionTimeTest
{
    class Program
    {
        // Batch account credentials
        private const string BatchAccountName = "REDACTED";
        private const string BatchAccountKey = "REDACTED";
        private const string BatchAccountUrl = "REDACTED";

        private const string JobId = "testjob";
        private const string TaskId = "three-day-retention-test";

        static void Main(string[] args)
        {
            BatchSharedKeyCredentials cred = new BatchSharedKeyCredentials(BatchAccountUrl, BatchAccountName, BatchAccountKey);
            using (BatchClient batchClient = BatchClient.Open(cred))
            {
               var task = new CloudTask(TaskId, "sleep 10")
                {
                    Constraints = new TaskConstraints()
                    {
                        RetentionTime = TimeSpan.FromDays(3)
                    }
                };

                Console.WriteLine($"Retention time in: {task.Constraints.RetentionTime}");
                batchClient.JobOperations.AddTask(JobId, task);
                Console.WriteLine($"task {TaskId} added!");

                var taskInService = batchClient.JobOperations.GetTask(JobId, TaskId);
                Console.WriteLine($"Retention time out: {taskInService.Constraints.RetentionTime}");
            }
        }
    }
}
```

Sample output on the console:

> Retention time in: 3.00:00:00
> task three-day-retention-test added!
> Retention time out: 3.00:00:00

Portal output:

<img width="328" alt="Constraints" src="https://user-images.githubusercontent.com/253383/127178793-4d787719-5ffc-49bb-b898-0896b8857e51.png">

Hopefully, the code sample helps! If not, could you show a bit more code so we can maybe spot the issue.

**Comment by christophwille** [comment]
Confirm it working - I had multiple paths creating CloudTask, and I had accidentially picked the wrong one.
