### ISSUE TITLE
NVIDIA driver version bundled in Ubuntu Server container image is behind latest

### ISSUE THREAD

**Issue by okofish** [Azure/Batch#116]
#### Problem Description

The NVIDIA GPU driver version bundled in the ["Ubuntu for Azure Batch container pools"](https://portal.azure.com/#blade/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/microsoft-azure-batch.ubuntu-server-container/product/) is 460.32.03 (January 2021), which is behind the latest production version from NVIDIA (470 branch; July 2021). (See [NVIDIA's driver lifecycle policy](https://docs.nvidia.com/datacenter/tesla/drivers/index.html#lifecycle).)

#### Steps to Reproduce

- Create a new pool using the "Ubuntu for Azure Batch container pools" VM image (Publisher: `microsoft-azure-batch`; Offer: `ubuntu-server-container`; Sku: `20-04-lts`). Select a VM size in the NCv3 series. Enable container support for the pool nodes (set "Container configuration" to "Custom" in the pool creation UI).
- Scale the pool up to 1 node.
- Once the node reaches the "idle" state, SSH into it (this can be done easily with Batch Explorer).
- Run the `nvidia-smi` command.

#### Expected Results

The GPU driver version on the node is in the [470 family](https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-470-57-02/index.html), which is the latest production branch released by NVIDIA, released in July 2021.

#### Actual Results

The driver version is [460.32.03](https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-460-32-03/index.html), released in January 2021:
```
batch-explorer-user@63c58fa129ae469aa7f4dbc8e4120775000000:~$ nvidia-smi
Tue Oct 26 17:18:31 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
(...)
```

#### Additional Logs

This can be additionally confirmed by manually starting an Azure VM, outside of Batch, using the ["Ubuntu for Azure Batch container pools"](https://portal.azure.com/#blade/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/microsoft-azure-batch.ubuntu-server-container/product/) image.

The VM's filesystem will contain the NVIDIA driver installer packages under the `/opt/batch/bootstrap/` directory. The driver version can be seen to be 460.32.03, and the modification date on the installer files is in May 2021.
```
azureuser@batch-image-test:~$ ls -l /opt/batch/bootstrap/
total 852064
-rwxr-xr-x 1 azureuser azureuser      6379 May 11 21:30 azbatch_image_script.sh
-rw-r--r-- 1 azureuser azureuser 178089544 May 11 21:30 nc_nvidia.run
-rwxr-xr-x 1 root      root      250920763 May 11 21:38 nc_nvidia_custom.run
-rw-r--r-- 1 azureuser azureuser 183364599 May 11 21:30 nv_nvidia.run
-rwxr-xr-x 1 root      root      258650905 May 11 21:35 nv_nvidia_custom.run
-rw-r--r-- 1 azureuser azureuser   1474560 May 11 21:30 nvidia-docker.tar

azureuser@batch-image-test:~$ /opt/batch/bootstrap/nc_nvidia_custom.run --info

  Identification    : NVIDIA Accelerated Graphics Driver for Linux-x86_64 460.32.03
  Target directory  : NVIDIA-Linux-x86_64-460.32.03-custom
  Uncompressed size : 625302 KB
  Compression       : gzip
  Date of packaging : Tue May 11 21:37:00 UTC 2021
  Application run after extraction : ./nvidia-installer

  The directory NVIDIA-Linux-x86_64-460.32.03-custom will be removed after extraction.
```

#### Additonal Comments

My company is developing an integration between our software product and Azure Batch, but our product depends on a GPU driver version >= 470.42. We could potentially package a custom version of the Batch VM image with a new GPU driver installer, but for obvious reasons I would much prefer to stick to the official, verified, Microsoft-provided images.

As a note: the NVIDIA GPU driver extension for Azure Linux VMs [is currently on the 470 branch](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup#nvidia-grid-drivers), so it seems to be just the Batch-specific image that's behind on this (rather than Azure in general).

**Comment by okofish** [comment]
Hi, are there any updates on the status of/plans for the next Ubuntu container image release?

**Comment by staer** [comment]
There was an issue building the Nvidia drivers which we believe has now been resolved in one of the newer driver releases for Linux. I can't give an exact time frame, but the driver build issue has hopefully been resolved which will unblock our build pipeline. I will update this thread when I have more definitive information.

**Comment by okofish** [comment]
Thank you @staer, I very much appreciate that and any further updates.

**Comment by staer** [comment]
The driver should be updated to at least 470.82.01 on all the latest images. Our publishing of images doesn't directly coincide when new drivers are released though, so from time to time, the driver version may be a version or so behind.
