### ISSUE TITLE
Autoscale formula shows wrong percentage

### ISSUE THREAD

**Issue by anibaldk** [Azure/Batch#120]
#### Problem Description
The $PendingTasks.GetSamplePercent() function seems to return an incorrect percentage.
I modified the standard formula slightly to show the issue using a max between the actual sample and the min number of VMs

#### Steps to Reproduce
`startingNumberOfVMs = 1;
maxNumberofVMs = 25;
pendingTaskSamplePercent = $PendingTasks.GetSamplePercent(180 * TimeInterval_Second);
pendingTaskSamples = pendingTaskSamplePercent < 30 ? startingNumberOfVMs : max(startingNumberOfVMs, avg($PendingTasks.GetSample(180 * TimeInterval_Second)));
$TargetDedicatedNodes=min(maxNumberofVMs, pendingTaskSamples);
`
There are jobs in an active state but all tasks are completed.
There are no running/scheduled/pending tasks at all.

#### Expected Results
pendingTaskSamplePercent = 0
pendingTaskSamples = 1

#### Actual Results
pendingTaskSamplePercent = 100
pendingTaskSamples = 1
Which indicates the `avg($PendingTasks.GetSample(180 * TimeInterval_Second)` to be 0, which is correct but inconsistent with the percent being 100.

#### Additonal Comments
The `PendingTasks.GetSample()` seems correct. It's only the percentage which brings out erroneous data.
Pool type is batch.node.ubuntu 20.04 | DockerCompatible.

**Comment by alfpark** [comment]
You will need to file a support request so that the team can investigate your issue for your particular account and pool.
