### ISSUE TITLE
Timeline for enabling Easv5 (and others)

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/Batch#121]
Apologies if this is the wrong place to ask this, but is there a timeline for when new VM sizes (such as [Easv5](https://docs.microsoft.com/en-us/azure/virtual-machines/easv5-eadsv5-series)) are going to be available to select for [Azure Batch Pools](https://docs.microsoft.com/en-us/azure/batch/batch-pool-vm-sizes)?

**Comment by staer** [comment]
I'll check on this, as of right now it's still not supported

**Comment by staer** [comment]
The Eadsv5-series is supported but the Easv5-series is not due to lack of ephemeral OS disk which is not currently support in Batch

**Comment by MatthewSteeples** [comment]
@staer Do you mean ephemeral OS disk or the lack of a temporary disk? The [docs](https://learn.microsoft.com/en-us/azure/batch/create-pool-ephemeral-os-disk) reckon that ephemeral OS disks are supported. It's possible that I've misunderstood exactly what the problem is.

**Comment by alfpark** [comment]
Local temporary disk: https://learn.microsoft.com/azure/batch/batch-pool-vm-sizes#pools-in-virtual-machine-configuration
