### ISSUE TITLE
Azure Batch fails to pull newer Docker images

### ISSUE THREAD

**Issue by ghost** [Azure/Batch#122]
#### Problem Description

Hello. I'm running Docker images from ACR in Batch. The auth routine is done by managed identity. Pool is set up with user-assigned managed identity and has ACR attached.

Everything works fine for some time. But in a few hours/days tasks cannot pull newer Docker images from ACR due to unauthorized error. The way to fix it right now is to reboot the node - after node reboot, tasks can again pull images for few hours. But after some time the problem occurs again. 

#### Steps to Reproduce
1. Create a pool with the following settings:
    * Publisher: microsoft-azure-batch
    * Offer: ubuntu-server-container
    * SKU: 20-04-lts
    * Version: latest
    * User-assigned identities: add new
    * Container type: dockerCompatible
    * Container registries:
    ** Server: xxxx.azurecr.io
    ** Identity reference: add pool identity here
2. Create a task which will use any container from the ACR referenced in pool.
3. Ensure everything works.
4. Wait few hours (more then 3)/day, and create a task again but with _different image\tag_ 

Obviously, user-assigned managed identity for pool needs to have AcrPull role in ACR.

#### Expected Results

Task works.
#### Actual Results

Category: UserError
Code: ContainerInvalidImage
Message: One or more container images specified are invalid
Name: ContainerImage

Value:
Get https://xxxxx.azurecr.io/v2/yyyy: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.

#### Additonal Comments
I also tried to add container registry spec into task spec though it's not required per portal information. That didn't help.
Node size: standard_d4_v3
Node agent version: 1.9.22

Another thing I tried to troubleshoot is to manually install az cli and try to pull image manually from the node via 
```
sudo az login --identity
sudo az acr login -n yyyy
docker pull ...
```
And that worked. But tasks cannot pull image anyway till node is rebooted.

**Comment by gtrubach-iballistix** [comment]
I was able to find only one log in agent-debug.log for login into docker registry on node start.

```
■■20220202T110002.693Z■00000000-0000-0000-0000-000000000000■DEBUG■agent.user■user.py■_add_user_posix_async■1902■5169■MainThread■140515222252416■setting login disabled password as password not specified for user _azbatch
■■20220202T110007.557Z■ed4007be-8416-11ec-b852-000d3a47328b■INFO■agent.user■user.py■apply_pool_user_configuration_async■661■5169■MainThread■140515222252416■apply pool user configuration for username=_azbatch admin=False ssh_cidr_pattern=None uid=None gid=None windows_user_login_mode=None
■■20220202T110008.347Z■00000000-0000-0000-0000-000000000000■DEBUG■agent.container.containerutil■containerutil.py■login_container_registries_async■93■5169■MainThread■140515222252416■login registries status: Status.Ok
```

I don't see this log anymore. So my guess is that ACR authentication is expiring and thus tasks cannot pull images after some time.

**Comment by gtrubach-iballistix** [comment]
After further investigation, I found, that according to the log auth works when registry setting is specified for the task.

```
■■20220202T124251.879Z■00000000-0000-0000-0000-000000000000■INFO■agent.container.container_client.docker■docker.py■_set_user_internal■1138■1076■ThreadPoolExecutor-4_0■139634512455424■Auth user 00000000-0000-0000-0000-000000000000 for registry XXXX.azurecr.io succeeded
```

But still, images cannot be pulled due to unauthorized error

```
■■20220202T125331.600Z■00000000-0000-0000-0000-000000000000■ERROR■agent.container.containermanager■containermanager.py■_process_add_image_name_request_async■154■1076■MainThread■139634623130624■pull image XXX.azurecr.io/YYY:0.1.0-5 failed.□
Traceback (most recent call last):□  File "docker/api/client.py", line 259, in _raise_for_status□  File "requests/models.py", line 943, in raise_for_status□requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/images/create?tag=0.1.0-5&fromImage=XXX.azurecr.io%2FYYY□□During handling of the above exception, another exception occurred:□□
Traceback (most recent call last):□  File "agent/container/container_client/docker.py", line 1561, in prepare_image_async□  File "common/util/retry.py", line 195, in retry_helper_async□  File "common/util/retry.py", line 184, in retry_helper_async□  File "agent/container/container_client/docker.py", line 1472, in async_method□  File "concurrent/futures/thread.py", line 57, in run□  File "docker/api/image.py", line 415, in pull□  File "docker/api/client.py", line 261, in _raise_for_status□  File "docker/errors.py", line 31, in create_api_error_from_http_exception□docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://XXX.azurecr.io/v2/YYY/manifests/0.1.0-5: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.")□□The above exception was the direct cause of the following exception:□□Traceback (most recent call last):□  File "agent/container/containermanager.py", line 144, in _process_add_image_name_request_async□  File "agent/container/container_client/docker.py", line 1574, in prepare_image_async□agent.container.container_client.errors.ContainerException: Get https://XXX.azurecr.io/v2/YYY/manifests/0.1.0-5: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

**Comment by staer** [comment]
Thanks for the report, I will look into this. It sounds like it could be a caching issue on the identity token

**Comment by gtrubach-iballistix** [comment]
@staer - Sorry to bother you, but do you have any update on this?

**Comment by staer** [comment]
Not bother at all! I believe I've identified the issue and am trying to figure out a fix.  The issue seems rooted in that when we exchange a managed identity token for an ACR access token, that token has its own lifespan which needs to be managed outside of normally managed identity tokens.

**Comment by gtrubach-iballistix** [comment]
@staer Hello, are there any updates on this?

**Comment by staer** [comment]
This has been fixed and merged into the codebase, it will go out with the next agent release. I will update the thread when this happens.

**Comment by KehindeOwens** [comment]
Hello @staer, do you have an approximate ETA on when the next agent release will go out?

**Comment by staer** [comment]
No ETA at the moment, we are awaiting a few other fixes before doing a release.

**Comment by czietsman** [comment]
Is there a potential workaround for this while we wait?

**Comment by KehindeOwens** [comment]
@czietsman If it helps, we restart our batch nodes via a script in order to workaround this issue until the release is published. Restarting the nodes clears the cache and gets us around the issue. Flaky but works

**Comment by staer** [comment]
This fix is part of the release that is going out right now, it has hit several regions and should be fully available in all of the public regions azure within the next week or so. I will close the thread when the release finishes (I will also update the release notes today).

**Comment by czietsman** [comment]
Thanks, I've switched to password based authentication in the mean time and
will revert back to user managed identity as soon as the release is
complete.

**Comment by staer** [comment]
The release has been completed. The underlying issue was that managed identity tokens were being exchanged with the ACR OAuth endpoint but the tokens that endpoint returned had a limited lifespan outside the lifespan of the original MI token. This has been addressed by re-requesting the OAuth token from ACR when needed.

**Comment by tiffanyseale** [comment]
I am seeing this when I spin up a new pool. The nodes start successfully, one task completes and all others fail, on node restart it completes all of them successfully.

**Comment by dfs-sanket-patel** [comment]
I am still facing this issue lets say my node is running and if i pushed image to ACR with the latest tag. when i run the task it is not able to fetch the latest image any solution? i tried both approach password and managed identity still same result
