### ISSUE TITLE
Support for Standard_Dads_v5 SKU

### ISSUE THREAD

**Issue by hgoodrow** [Azure/Batch#126]
#### Feature Request Description
Have a compute need that shows the best price vs performance when using the Standard_Dads_v5 SKU 

#### Describe Preferred Solution
The Standard_Dads_v5 SKU is new and Azure Batch cannot yet use this SKU.

**Comment by staer** [comment]
This SKU is being onboarded and will be available in a future release

**Comment by MatthewSteeples** [comment]
Related, but is there a plan to bring the Ev5 series on board too?

**Comment by staer** [comment]
This is family is now supported:

> $ az batch location list-skus --location eastus | grep standardDADSv5Family | wc -l
> 8
