### ISSUE TITLE
Windows: Are task working directories re-used when retrying?

### ISSUE THREAD

**Issue by letmaik** [Azure/Batch#14]
I came across a case where it seemed that the working directory of a task is re-used if the task fails and is retried. If this is true (I couldn't find anything in the docs), then I find that quite dangerous as most scripts assume a fresh working directory and may fail if files exist already. Please confirm if this is the case for Windows nodes.

One solution is to change the task script to always clean the working directory at the start of each task, just in case. The other solution is to make the script fully resumable such that it can handle partially finished work, but this is a lot harder in general.

**Comment by matthchr** [comment]
If you're asking about retries configured by the user (i.e. by setting MaxRetryCount > 0) then yes, the same directory is used. This is in order to save having to re-download any resource files, application packages, etc just for a local retry. If we cleaned everything up and re-downloaded things it could add significant time for most applications.

If you have retries configured for your task _and_ expect a fresh directory, you should perform some cleanup at the start of your script as you suggest.

**Comment by letmaik** [comment]
Thanks for the clarification. Is this documented anywhere? I find this quite important to know for developers.

**Comment by alfpark** [comment]
Tagging @dlepow for docs.

**Comment by dlepow** [comment]
@mattchr @alfpark - I see a little bit about this in the REST API doc, for maxRetryCount, in  https://docs.microsoft.com/en-us/rest/api/batchservice/task/addcollection or https://docs.microsoft.com/en-us/rest/api/batchservice/task/add: "Resource files and application packages are only downloaded again if the task is retried on a new compute node." Perhaps we could expand this to something like "By default, Bath retries a task in the same working directory and compute node where the task ran previously. Resource files and application packages.... etc."?

**Comment by matthchr** [comment]
I think we could update maxRetryCount to have this additional text:
> When a task is retried it may be retried on the same node or a different node. When retried on the same node, the task is executed from the directory where it previously ran, and makes use of the same application packages and resource files that were originally downloaded for the task. Resource files and application packages are downloaded again only if the task is retried on a new compute node.

rather than this which is what we say now:
> Resource files and application packages are only downloaded again if the task is retried on a new compute node.

@dlepow, @alfpark, @darylmsft - thoughts?
@xingwu1 - if folks agree, can we roll this into our upcoming Swagger change?

**Comment by darylmsft** [comment]
I like the proposed text.

**Comment by dlepow** [comment]
@matthchr - LGTM! Thanks.

**Comment by alfpark** [comment]
The retry concept is a bit loaded (we're trying to work towards making more of this information available). To clarify on the download portion of retry:

Resource files and app packages can be downloaded again if the task is allowed to retry regardless of which compute node the service selects. It will not download these files again if the service elects to immediately retry the task on the same node and the downloads were successful.

**Comment by matthchr** [comment]
Update to this -- we've actually changed (fixed) the behavior to always use a fresh directory to avoid customers having to deal with this bit of detail.

As such, I'm updating our documentation to properly reflect this.

Thanks for raising this issue @letmaik

**Comment by matthchr** [comment]
@alfpark I think we can probably close this given the above state
