### ISSUE TITLE
Microsoft.Azure.Management.Batch - deprecated

### ISSUE THREAD

**Issue by BC89** [Azure/Batch#155]
Greetings,

Why is there no notification or announcement mentioned regarding Microsoft.Azure.Management.Batch being deprecated? Am I misunderstanding what MS is telling me in the VS ide? 

![image](https://user-images.githubusercontent.com/3298355/227536519-ff289fc3-424d-405b-a039-891ac8cd9050.png)

Thx!

**Comment by MatthewSteeples** [comment]
The right hand side of that window should have given you some further details, but they can also be found on [NuGet](https://www.nuget.org/packages/Microsoft.Azure.Management.Batch). The summary is that you should migrate to the new SDK - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md

**Comment by BC89** [comment]
There seems to be scant to no specific migration documents or samples. Anything more MS can provide? Also, shouldn't the readme be updated?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Matthew Steeples ***@***.***>
Sent: Friday, March 24, 2023 10:27:30 AM
To: Azure/Batch ***@***.***>
Cc: Brendan Carroll ***@***.***>; Author ***@***.***>
Subject: [External Email] Re: [Azure/Batch] Microsoft.Azure.Management.Batch - deprecated (Issue #155)


***From ***@***.*** 410-316-7820 *** This is an External Email from outside of KCI.***
________________________________
The right hand side of that window should have given you some further details, but they can also be found on NuGet<https://www.nuget.org/packages/Microsoft.Azure.Management.Batch>. The summary is that you should migrate to the new SDK - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md<https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md>

**Comment by dpwatrous** [comment]
@BC89 To elaborate a bit on what MatthewSteeples said, this is part of an Azure-wide rework of the SDKs.

Besides the migration guide linked above, [this page](https://azure.microsoft.com/blog/previewing-azure-sdks-following-new-azure-sdk-api-standards/) has information about ongoing support, and [this blog post](https://azure.microsoft.com/blog/previewing-azure-sdks-following-new-azure-sdk-api-standards/) has some context on the overall effort.

I created a PR to add this information to the package's Readme: https://github.com/Azure/azure-sdk-for-net/pull/35167

**Comment by BC89** [comment]
Where is the repo specific to the Azure Batch Managment SDK? Examples, unit tests? This seems really like a half-harted effort to check a box., honestly.

**Comment by dpwatrous** [comment]
It's the same repository. The new package is Azure.ResourceManager.Batch and is located at https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/batch/Azure.ResourceManager.Batch
