### ISSUE TITLE
Access Node files from Dockers container

### ISSUE THREAD

**Issue by sa1sen** [Azure/Batch#159]
Hi,

I am using the SDK for Azure Batch to create jobs, pools and tasks. My requirement is to read a docker image from Azure Container Registry, pass in a file (stored in Azure Blob), and get output files back. How can I pass in input files stored on Pool nodes (resource files) to docker containers?

I have tried -v (to mount) and copying files directly but no luck. 

Thanks

**Comment by staer** [comment]
When you ssh into the box, you can run `docker inspect XXX` where XXX is a conatiner id and it will show you the mount mapping (and all the other run options)
