### ISSUE TITLE
Accessing files from resource files as part of docker container orchestration

### ISSUE THREAD

**Issue by sa1sen** [Azure/Batch#160]
Referencing closed issue: [https://github.com/Azure/Batch/issues/159]

Using resource files, I see a file copied to tasks working directory in root/wd/xxxx.txt (this I presume is the root node). But where can I see where exactly it is mapped in docker container, i.e. where will this be located in dockers volume? I have tried SSHing into the node and then exploring the container but no luck.

Is there deeper documentation/tutorial on using container images and Azure batch?

**Comment by staer** [comment]
@sa1sen,

I did a quick test on a pool for you to hopefully help illustrate what is going on. In this case i'm creating a pool using the ubuntu-hpc:2004 image (container supported image) and then submitting a task that pulls the CHANGELOG for batch from github and then spawns a container process which will just do "ls -la && pwd && echo $AZ_BATCH_TASK_WORKING_DIR

{
  "id": "container-test-task",
  "url": "REDACTED",
  "eTag": "0x8DB8D24C593346F",
  "lastModified": "2023-07-25T15:35:27.615Z",
  "creationTime": "2023-07-25T15:35:27.615Z",
  "state": "completed",
  "stateTransitionTime": "2023-07-25T15:35:35.002Z",
  "previousState": "running",
  "previousStateTransitionTime": "2023-07-25T15:35:33.692Z",
  **"commandLine": "/bin/bash -c \"ls -la && pwd && echo AZ_BATCH_TASK_WORKING_DIR=$AZ_BATCH_TASK_WORKING_DIR\"",**
  **"containerSettings": {
    "imageName": "ubuntu:20.04",**
    "workingDirectory": "taskWorkingDirectory"
  },
  **"resourceFiles": [
    {
      "httpUrl": "https://raw.githubusercontent.com/Azure/Batch/master/changelogs/nodeagent/CHANGELOG.md",
      "filePath": "CHANGELOG.md"
    }**
  ],
  "environmentSettings": [],
  "constraints": {
    "maxWallClockTime": "P10675199DT2H48M5.4775807S",
    "retentionTime": "P7D",
    "maxTaskRetryCount": 0
  },
  "requiredSlots": 1,
  "userIdentity": {
    "autoUser": {
      "scope": "pool",
      "elevationLevel": "nonadmin"
    }
  },
  "executionInfo": {
    "startTime": "2023-07-25T15:35:33.737Z",
    "endTime": "2023-07-25T15:35:35.002Z",
    "exitCode": 0,
    "containerInfo": {
      "containerId": "fd8c4015b77a4db6c0b1201e88d9d6b22d73e065ebbc1e799c58ad64f11b44ff",
      "state": "exited"
    },
    "retryCount": 0,
    "requeueCount": 0,
    "result": "success"
  },
  "nodeInfo": {
    "affinityId": "TVM:REDACTED",
    "nodeUrl": "REDACTED",
    "poolId": "container-test",
    "nodeId": "REDACTED",
    "taskRootDirectory": "workitems/test-job/job-1/container-test-task",
    "taskRootDirectoryUrl": "REDACTED"
  }
}

stdout.txt from this task is as follows:

total 40
drwxr-x--- 2 _azbatch _azbatchgrp  4096 Jul 25 15:35 .
drwxr-xr-x 4 _azbatch _azbatchgrp  4096 Jul 25 15:35 ..
-rwxrwx--- 1 _azbatch _azbatchgrp 31386 Jul 25 15:35 CHANGELOG.md
/mnt/batch/tasks/workitems/test-job/job-1/test-task-4/wd
**AZ_BATCH_TASK_WORKING_DIR=/mnt/batch/tasks/workitems/test-job/job-1/test-task-4/wd**

So what we can see here is that the resource file (CHANGELOG.md) was downloaded to the host and then the AZ_BATCH_TASK_WORKING_DIR was mapped into the container. In this case the path within the container is /mnt/batch/tasks-workitems/test-job/job-1/test-task-4/wd, however we should just use the environment variable AZ_BATCH_TASK_WORKING_DIR as this is automatically mapped on both the host and within the container so you don't have to worry about paths too much.

https://learn.microsoft.com/en-us/azure/batch/batch-docker-container-workloads#container-task-working-directory

Hope this makes things more clear!

**Comment by sa1sen** [comment]
Thank you so much!

I can confirm now the environment variables are working and I can pass dynamically the input files!
