### ISSUE TITLE
Ubuntu 22.04 Marketplace Images Fail to Mount Azure File Shares or CIFS filesystems

### ISSUE THREAD

**Issue by alfpark** [Azure/Batch#164]
## Impact

There is a known issue with Canonical Ubuntu 22.04 LTS images where Azure File Shares or CIFS filesystems will fail to mount due to a missing kernel module (cifs.ko). As of 2023-11-03, this affects image version `22.04.202311010` which currently maps to `latest`.

## Workarounds

There are only two workarounds for this issue in Batch if you leverage [pool-level VFS functionality](https://learn.microsoft.com/azure/batch/virtual-file-mount):

1. Pin your pool's version to `22.04.202310260` and recreate your pool. You currently cannot update a pool's version. Do not reboot these machines if auto-patching/auto-update is enabled within the image/OS as this will update the kernel. Separately, you can mark the affected packages as held back if you wish to maintain this behavior but not opt into the affected kernel. Please see the linked bug below for more details. Please also understand that by pinning to a prior version, you are opting out of any security and important fixes that the newer image would provide. If this is unacceptable, follow the next suggestion as a workaround.
1. [Create and utilize a custom image](https://learn.microsoft.com/azure/batch/batch-sig-images). As part of the custom image preparation, execute: `apt-get install -y linux-modules-extra-azure`

If you do not use pool-level VFS functionality and have custom mounting code in your start task or job prep/tasks, then you can install the `linux-modules-extra-azure` as part of your start task to remediate temporarily.

## Upstream Fix ETA

We do not have an ETA for when this issue will be fixed as it is a bug with the image's publisher, Canonical. You can refer to these bugs for tracking:

- https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/2042092
- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2042546

**Comment by dxyinme** [comment]
This bug has been fixed in latest Canonical Ubuntu22.04 image.
version: **22.04.202312060**
