### ISSUE TITLE
Beyond Linux 20-04-lts

### ISSUE THREAD

**Issue by BC89** [Azure/Batch#166]
Will Azure Batch ever move to a more recent Linux version for running containerized solutions?  As it is, we are stuck in time at 20-04-lts, batch.node.ubuntu 20.04 when publisher is microsoft-azure-batch. If you try setting publisher to canonical and 22.04 it fails in a docker container scenario.

**Comment by alfpark** [comment]
Batch support of containers is independent of the VM image. Some VM images, like the one you are referencing have built-in container support. You can discover VM images with the `DockerCompatible` capability using the [`ListSupportedImages` API](https://learn.microsoft.com/rest/api/batchservice/account/listsupportedimages), [PowerShell](https://learn.microsoft.com/powershell/module/az.batch/get-azbatchsupportedimage), or [Azure CLI](https://learn.microsoft.com/cli/azure/batch/pool/supported-images). You can also create your own custom image that meets the necessary requirements to be compatible with containers on Batch.

The most direct upgrade path is probably `microsoft-dsvm` `ubuntu-hpc` `2204`.

**Comment by BC89** [comment]
Thank you very much. This set me in the right direction. Much appreciated.
________________________________
From: Fred Park ***@***.***>
Sent: Friday, January 19, 2024 2:51 PM
To: Azure/Batch ***@***.***>
Cc: Brendan Carroll ***@***.***>; Author ***@***.***>
Subject: [External Email] Re: [Azure/Batch] Beyond Linux 20-04-lts (Issue #166)


***From ***@***.*** 410-316-7820 *** This is an External Email from outside of KCI.***
________________________________
Batch support of containers is independent of the VM image. Some VM images, like the one you are referencing have built-in container support. You can discover VM images with the DockerCompatible capability using the ListSupportedImages API<https://learn.microsoft.com/rest/api/batchservice/account/listsupportedimages>, PowerShell<https://learn.microsoft.com/powershell/module/az.batch/get-azbatchsupportedimage>, or Azure CLI<https://learn.microsoft.com/cli/azure/batch/pool/supported-images>. You can also create your own custom image that meets the necessary requirements to be compatible with containers on Batch.

The most direct upgrade path is probably microsoft-dsvm ubuntu-hpc 2204.
