### ISSUE TITLE
Support for `standardNDSH100v5Family` vmfamily

### ISSUE THREAD

**Issue by BMurri** [Azure/Batch#173]
Is there a plan to support the `standardNDSH100v5Family` (e.g. the `Standard_ND96isr_H100_v5` SKU)?

**Comment by alfpark** [comment]
This VM family is supported in select regions. Please consult the [docs](https://learn.microsoft.com/azure/batch/batch-pool-vm-sizes#pools-in-virtual-machine-configuration) to utilize the List API for this purpose.
