### ISSUE TITLE
An error occurred when creating a pool using batch shipyard

### ISSUE THREAD

**Issue by ZhangZeKai123** [Azure/Batch#186]
The vm image used before was microsoft-azure-batch 20-04-lts. Since it will be discontinued on April 23, 2025, the following error occurred when upgrading to microsoft-dsvm 2204: "ValueError: unsupported Docker (and/or GPU) Host VM Config, publisher=microsoft-dsvm offer=ubuntu-hpc sku=2204 vm_size=standard_d2_v3"，Is it because batch shipyard does not support higher versions of Ubuntu, or is there some other reason?

**Comment by alfpark** [comment]
Batch Shipyard is no longer supported. See issue #147 along with the clear archival state of the GitHub repo and README stating that it is no longer supported.
