### ISSUE TITLE
New-AzureBatchPool example 2 not working

### ISSUE THREAD

**Issue by dedreira** [Azure/Batch#21]
Hi,

I'm trying to make work the example number 2 of the New-AzureBatchPool powershell command reference page:

https://docs.microsoft.com/en-us/powershell/module/azurerm.batch/new-azurebatchpool?view=azurermps-6.8.1#examples

 $imageReference = New-Object -TypeName "Microsoft.Azure.Commands.Batch.Models.PSImageReference" -ArgumentList @("WindowsServer", "MicrosoftWindowsServer", "2016-Datacenter", "*")
 $configuration = New-Object -TypeName "Microsoft.Azure.Commands.Batch.Models.VirtualMachineConfiguration" -ArgumentList @($imageReference, "batch.node.windows amd64")
 New-AzureBatchPool -Id "MyPool" -VirtualMachineSize "Small" -VirtualMachineConfiguration $configuration -TargetDedicatedComputeNodes 3 -BatchContext $Context
And I'm always receiving the error message: New-AzureBatchPool : Operation returned an invalid status code 'BadRequest'

As example 1 works like a charm, I'm starting to believe that the problem could reside in the object PSVirtualMachineConfiguration . . . anyone knows how to make it work? 

Thanks

**Comment by brnleehng** [comment]
This is a duplicate issue that was answered on the forums (https://social.msdn.microsoft.com/Forums/azure/en-US/d6960627-4a79-4ba5-a08e-b161824b4f74/newazurebatchpool-reference-page-example-2-not-working?forum=azurebatch).

Let us know if you are running into any other issues

Thanks,
Brian

**Comment by darylmsft** [comment]
The linked issue has a workaround.
