### ISSUE TITLE
Add counters for active/running tasks

### ISSUE THREAD

**Issue by sylr** [Azure/Batch#29]
#### Feature Request Description
We want to be able to have precise batch metrics, especially task volume metrics.

#### Describe Preferred Solution
At this time the active & running task metrics are gauge metrics describing the amount of active/running tasks at a given time. Although useful it would be great to have also total counters for active & running tasks to be able to compute volumes (delta).

Current
```go
// TaskCounts ...
type TaskCounts struct {
    autorest.Response `json:"-"`
    Active            *int32 `json:"active,omitempty"`
    Running           *int32 `json:"running,omitempty"`
    Completed         *int32 `json:"completed,omitempty"`
    Succeeded         *int32 `json:"succeeded,omitempty"`
    Failed            *int32 `json:"failed,omitempty"`
}
```
Proposed
```go
// TaskCounts ...
type TaskCounts struct {
    autorest.Response `json:"-"`
    Active            *int32 `json:"active,omitempty"`
    ActiveTotal       *int32 `json:"active_total,omitempty"`
    Running           *int32 `json:"running,omitempty"`
    RunningTotal      *int32 `json:"running_total,omitempty"`
    CompletedTotal    *int32 `json:"completed_total,omitempty"`
    SucceededTotal    *int32 `json:"succeeded_total,omitempty"`
    FailedTotal       *int32 `json:"failed_total,omitempty"`
}
```

#### Additional Context
I asked this because after writing [prometheus-azure-exporter](https://github.com/sylr/prometheus-azure-exporter) (which was initially written only to expose Azure Batch metrics to prometheus) we couldn't represent accurately active & running tasks because gauges do not show what happens between two metrics retrievals.

**Comment by sylr** [comment]
cc @devigned @kiwidev

**Comment by devigned** [comment]
@sylr I'm not a committer on this project, but sounds like a useful feature. 👍

**Comment by sylr** [comment]
@devigned do you know who are ?

**Comment by devigned** [comment]
I'm not sure, but I think @matthchr probably does.

**Comment by matthchr** [comment]
Thanks for the ping @devigned 
@sylr - I've forwarded this along internally to the owners of the counting features.

**Comment by sylr** [comment]
@matthchr Thanks!

Any chance to have feedbacks from these guys here ?

**Comment by matthchr** [comment]
Hi @sylr - just making sure we understand this correctly.

Currently, `Active`, `Completed`, etc are snapshots of the current number of tasks in the given state at the time you call the metrics API. It already includes _all tasks_ (so, `Active` + `Completed` + `Running` = total of all tasks).

What's the proposed difference between that behavior, and your `Total` proposal?
Is the primary desire you have to track tasks which have been deleted?

So for example if at `t0` you have:
```
20 active
10 running
10 completed
```

and then you delete the 20 active tasks, you'd like to see:
```
0 active
10 running
10 completed
20 TotalActive
```

Is that right?

**Comment by sylr** [comment]
The goal here is to track volumes of active and running tasks at any given time (before they complete or fail) by computing deltas.

Gauge don't allow to do that.

Also It would be nice to separate Failed and Canceled tasks because at the moment they all end up in the Failed counter. So this would be quite nice :

```
// TaskCounts ...
type TaskCounts struct {
    autorest.Response `json:"-"`
    // Current number of active tasks
    Active            *int32 `json:"active,omitempty"`
    // Total number of tasks ever created
    ActiveTotal       *int32 `json:"active_total,omitempty"`
    // Current number of running tasks
    Running           *int32 `json:"running,omitempty"`
    // Total number of tasks ever gone to running state
    RunningTotal      *int32 `json:"running_total,omitempty"`
    // Total number of tasks ever completed (SucceededTotal + FailedTotal + CanceledTotal)
    CompletedTotal    *int32 `json:"completed_total,omitempty"`
    // Total number of tasks ever succeeded
    SucceededTotal    *int32 `json:"succeeded_total,omitempty"`
    // Total number of tasks ever failed
    FailedTotal       *int32 `json:"failed_total,omitempty"`
    // Total number of tasks ever canceled
    CanceledTotal       *int32 `json:"failed_total,omitempty"`
}
```

**Comment by matthchr** [comment]
> The goal here is to track volumes of active and running tasks at any given time (before they complete or fail) by computing deltas.

Isn't this exactly what the current `Active`/`Running`/`Completed` already tell you? They're exactly the volume of tasks in a particular state at a particular time - why do you want/need to compute those numbers via deltas when they're already provided in the API?

If you want to compute deltas between time intervals, isn't subtracting `t0` from `t1` sufficient to see what has changed (unless you've deleted tasks - which is where my "are you deleting tasks" question came from)?

Sorry if I'm being dense - a specific example might help me understand the value of what you're asking for. I suspect my confusion is that I am not aware of how `prometheus` is doing things so it's not obvious why the current solution isn't sufficient.

**Comment by sylr** [comment]
```
  t       t+60     t+120    t+180    t+240       
  o--------o--------o--------o--------o
  0        2        1        3        0   active gauge
  o--------o--------o--------o--------o
 200      202      205      208      208  active total
  o--------o--------o--------o--------o
          +2       +3       +3       +0   delta(active total)
```

Here between t+60 and t+120 +3 new tasks but also 4 went to running

**Comment by matthchr** [comment]
Okay, so in the scenario you described, do you agree that the Batch API today would return the below (note that you didn't mention when completions happened so I just made some up)

```
  t       t+60     t+120    t+180    t+240       
  o--------o--------o--------o--------o
  0        2        1        3        0   active (as returned by the Batch API today)
  o--------o--------o--------o--------o
  0        0        4        1        0   running (as returned by the Batch API today)
  o--------o--------o--------o--------o
 200      200      200      204      208  completed (as returned by the Batch API today)
  o--------o--------o--------o--------o
 200      202      205      208      208  total tasks in the job (as computed by adding Active, Running, and Completed returned by the Batch API today)
  o--------o--------o--------o--------o
          +2       +3       +3       +0   delta (new tasks)
```

i.e. is your `active total` (which really is just == to the number of tasks added to the job) computable by summing `active`, `running`, and `completed`?

**Comment by sylr** [comment]
I believe you are correct, didn't see it that way.

**Comment by matthchr** [comment]
Note that, if your job deletes tasks, the above is a bit of a fib because delete tasks are omitted from counts, so deleting tasks does throw everything off (which is why I was asking about that scenario above).

If you aren't deleting tasks until the job is "done" then I _think_ the above should work for you?

**Comment by matthchr** [comment]
@alfpark - I think we can close this issue unless @sylr objects.

**Comment by sylr** [comment]
Huh yeah, still be nice to extract canceled jobs out of `Failed` counter and have its own `Canceled` counter.

**Comment by matthchr** [comment]
When you say `Canceled`, do you mean tasks which were terminated by the user via for example a `TerminateTask` API?

**Comment by sylr** [comment]
Yes.

**Comment by alfpark** [comment]
Closing, please open a feature request if needed.
