### ISSUE TITLE
How are tasks scheduled if the priority is the same for multiple jobs?

### ISSUE THREAD

**Issue by letmaik** [Azure/Batch#3]
The docs at https://docs.microsoft.com/en-gb/azure/batch/batch-api-basics#job-priority say:
> Within the same account, higher-priority jobs have scheduling precedence over lower-priority jobs.

In the Jobs section is says:
> When a job is submitted with a higher priority than jobs that are currently in progress, the tasks for the higher-priority job are inserted into the queue ahead of tasks for the lower-priority jobs. Tasks in lower-priority jobs that are already running are not preempted.

What happens if they have the same priority? Are the scheduled jobs then simply run one after another (job 1 finishes, then job 2 starts), or are the tasks of both jobs mixed together in the queue?

**Comment by matthchr** [comment]
If the jobs have the same priority, scheduling is intermixed, so tasks from each job have equal chance to be scheduled any time a node is free.
