### ISSUE TITLE
Allow some simple logic when task failed with application failures

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/Batch#36]
I can't really find it on documentation

I have task A,B,C
B will run when A success
C will run when A failed

When B is completed, C will have status Ignored (or something like that)
When C is completed, B will have status Ignored (or something like that)

Can we support this scenario?

I believe at this moment we only able to have
Task A, B
When A is failed, Block or Run B
When A is completed, Run B

**Comment by alfpark** [comment]
I'm not sure how your logic would work.

If `A -- success --> B` and `A -- fail --> C`, doesn't that mean tasks `B` and `C` starting/running are mutually exclusive? Both `B` and `C` could not both enter completed state.
