### ISSUE TITLE
Invalid parsing of Docker --mount arguments

### ISSUE THREAD

**Issue by jjcollinge** [Azure/Batch#39]
#### Problem Description
When using Docker [mounts](https://docs.docker.com/storage/bind-mounts/) as command line arguments via the  'Container run option' in Azure Batch such as:
`--mount type=bind,src=/path/to/src,dst=/path/to/dst,readonly`
Such an argument will result in the following error `ContainerInvalidSettings`. However, this is a valid Docker argument and you can use it if you run it directly with Docker on the Azure Batch node. Instead I've had to use the `-v` argument as a work around.

#### Steps to Reproduce
Execute an Azure Batch task that runs a Docker container and attempt to use the `--mount` argument by specifying it as a "Container run option".

#### Expected Results
The mount argument is correctly parsed and the normal Docker mount behaviour is observed.

#### Actual Results
A `ContainerInvalidSettings` error is returned.

**Comment by alfpark** [comment]
This has been fixed in [1.5.3](https://github.com/Azure/Batch/blob/master/changelogs/nodeagent/CHANGELOG.md#153---2019-03-12).
