### ISSUE TITLE
AutoScale formula not working when EnableInterNodeCommunication is set to true

### ISSUE THREAD

**Issue by dedreira** [Azure/Batch#40]
Hi,

I'm trying to create a pool with an autoscale formula and with internodecommunication enabled but I'm always getting this error:

> Code: AllocationTimedout
> 
> Message:
> Desired number of dedicated nodes could not be allocated as the resize timeout was reached
> 
> Details:
> n/a

#### Steps to Reproduce
Using this
AutoScale formula:
***************
$maxComputeNodeLimit=1;$minCapacity = 0;$LastSampledActiveTasks =$ActiveTasks.GetSample(1);$LastSampledRunningTasks =$RunningTasks.GetSample(1);$RunningAndWaiting = max($LastSampledActiveTasks, 0) + max($LastSampledRunningTasks, 0);$needcompute =$RunningAndWaiting >= 1;$nodesToAllocate =$RunningAndWaiting >$maxComputeNodeLimit ?$maxComputeNodeLimit:$RunningAndWaiting;$TargetDedicated =$needcompute ?$nodesToAllocate:$minCapacity;
***************
and with
InterNodeCommunicationEnabled = true

every time I create a pool with these parameters and I create a Job and a Task, the error appears, but if I set the property InterNodeCommunicationEnabled to false the error does not appear

Node Agent Sku: batch.node.centos 7
Publisher: microsoft-azure-batch

Thanks

**Comment by alfpark** [comment]
Internode comm enabled pools have a [maximum number of VMs that can be deployed](https://docs.microsoft.com/azure/batch/batch-quota-limit#pool-size-limits) at once.

Also, unless you're using the entire pool and applying the appropriate modifier, task samples may be insufficient for sizing metrics as only the master subtask is counted. We are working on a feature to improve this scenario.

**Comment by dedreira** [comment]
Hi alfpark!,

Yeah, but as you can see in the example I'd provided, the variable maxComputeNodeLimit is set to 1, and the maximun number of VMs that can be deployed is 1000 (and I do not have 999 VMs deployed to the batch account 😄 )

Anyway, I just recently discover the limitation with the autoscale formula that you point out in your comment. It would be fantastic to have the ability to resize the pool having in account multi-instance scenarios.
