### ISSUE TITLE
python parallel backend sample for batch, dask?

### ISSUE THREAD

**Issue by rquintino** [Azure/Batch#43]
For R we have doAzureParallel that I've used and worked great, 
Since then I mostly switched to python. Wondering if we could have a similar thing for python? Alternatively, be able to run dask on batch? (makes sense?)

thanks!
(superb work on batch, batch explorer, shipyard, congrats!)

**Comment by alfpark** [comment]
Currently there is no direct Batch integration with dask. Have you tried using the [k8s integration with dask](https://docs.dask.org/en/latest/setup/kubernetes.html) perhaps using AKS?

**Comment by rquintino** [comment]
Hi Fred, thanks, looking into it. Let me see!
(have seen this before but never tested, giving it a second look https://cloud4scieng.org/2018/05/17/parallel-programming-in-the-cloud-with-python-dask/)

still, it's not batch :) which is an amazing product :)
