### ISSUE TITLE
Node goes to unusable state when using GPU Container supported VMs in Azure batch pool

### ISSUE THREAD

**Issue by rjtshrm** [Azure/Batch#45]
#### Problem Description

I am trying to create a pool of GPU based Containers supported VMs. I have valid ContainerConfiguration and start task. The VM size is Standard_NC6. But whenever i create a pool it always goes to unusable state. If i remove ContainerConfiguration setting the node are in idle state but I dont see problem with ContainerConfiguration settings because If i choose the VM size standard_f2s_v2 (not-gpu) and keep the same ContainerConfiguration settings then it works fine and installs all images on machine. I think it has to do with some nvidia libraries installation while setting up the nodes

**Comment by alfpark** [comment]
Are you able to [egress the Batch service logs](https://docs.microsoft.com/cli/azure/batch/node/service-logs?view=azure-cli-latest)? You can also use the portal or Batch explorer to do so - but this operation may be unsuccessful on an unusable node. You may need to create a service request so we can examine further.

Ping @xingwu1.

**Comment by rjtshrm** [comment]
@xingwu1  I created VM with Configurations as follows microsoft-azure-batch (VM publisher), ubuntu-server-container (VM offer), 16-04-lts (Sku), batch.node.ubuntu 16.04 (Sku Id).

**Comment by xingwu1** [comment]
@rjtshrm The new image had been published. Re-create a new pool should work now.

**Comment by rjtshrm** [comment]
it worked. Thanks :+1: .
