### ISSUE TITLE
How to increase/expand D:\ Drive easily?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/Batch#48]
When defining a pool, we can define data disk.
This data disk should be automatically attached and expand D:\ drive where application and working directory used by batch

If not, is there any way to easily increase/expand D drive?

**Comment by alfpark** [comment]
The ephemeral disk cannot be expanded - the disk is local and static according to the VM size. You have a few options here:

1. Use a different VM with a larger ephemeral disk. Consult the Azure VM size documentation.
2. Copy your completed task data with the [output file feature](https://docs.microsoft.com/azure/batch/batch-task-output-files) to Azure Blob Storage. Delete the task after it completes or set a retention time on the task.
3. Attach a data disk and copy your data to the data disk after your task completes, then delete the task or set a retention time on the task. Alternatively, your task can directly write to somewhere on the data disk while it runs.
4. Mount an Azure Storage File Share and perform similar actions as 3 above. Note that Azure File Share may not meet your performance requirements.

**Comment by andrew-vandenbrink** [comment]
@alfpark thank you for your reply
