### ISSUE TITLE
How to use multiple images in a single pool?

### ISSUE THREAD

**Issue by xenalite** [Azure/Batch#49]
#### Problem Description
I want to know whats possible before I ask for a feature.
I have a static pool of VMs in Azure Batch. We use containers inside Batch nodes.
The pool is configured with a single image registry and a single Docker image as below:
![image](https://user-images.githubusercontent.com/4509839/54763226-80198800-4bed-11e9-85ab-923ea8db6317.png)

I then also have to specify the container settings on the task:
![image](https://user-images.githubusercontent.com/4509839/54763448-e7373c80-4bed-11e9-9568-428f61c8b74b.png)

If I specify an image in the task different to the one specified in the pool, I will get `ContainerInvalidImage` result - even if the image is in the same registry. From the screenshot below, the pool is configured with an image ending in `71299`, but the task is configured with an image ending in `74373`.

I have some questions:
1) How can I run multiple image versions in multiple tasks without having to specify those versions up front in the node pool? I do not know image versions ahead of the time to list all possible images I might use in the pool.

2) If a task container config has to match pool container config, then why do you need to specify both? One of those options is redundant. Either the pool is responsible for pulling images, or the task is.

3) If I cannot pull different image versions at runtime, can I amend the pool with new image versions? I attempted below code to amend an existing pool, but it does not seem possible according to the [API docs](https://docs.microsoft.com/en-us/rest/api/batchservice/pool/updateproperties#request-body).
```
private async Task<PoolInformation> GetExistingPool(BatchClient batchClient)
{
	var existingPool = await batchClient.PoolOperations.GetPoolAsync(_options.StaticPoolId);
	// The line below fails with System.InvalidOperationException: 'This object is in an invalid state.  Write access is not allowed.'
	existingPool.VirtualMachineConfiguration.ContainerConfiguration = CreateContainerConfig();
	await existingPool.CommitChangesAsync();
	return new PoolInformation {PoolId = existingPool.Id};
}
```

#### Expected Results
Node running the task should pull the missing image at runtime.

#### Actual Results
`ContainerInvalidImage` error.

**Comment by alfpark** [comment]
1. `containerImageNames` and `containerRegistries` are optional on [`ContainerConfiguration`](https://docs.microsoft.com/rest/api/batchservice/pool/add#containerconfiguration). Those are only needed if you want to pre-load Docker images on the pool so you do not incur the pull cost at task run time.
2. They don't need to match. Your intuition is correct. Did you provide the `containerRegistry` info on [`TaskContainerSettings`](https://docs.microsoft.com/rest/api/batchservice/task/add#taskcontainersettings)?
3. You should be able to pull whatever Docker image you need at task run time given that you've provided the correct credentials for private registries. You currently cannot patch or update existing pools with different container settings.

Can you provide more details about the `ContainerInvalidImage` error? There should be expanded error details with the error.

cc @xingwu1

**Comment by xenalite** [comment]
@alfpark Thanks for such a quick response. :)

> Can you provide more details about the ContainerInvalidImage error? There should be expanded error details with the error.

![image](https://user-images.githubusercontent.com/4509839/54767403-fc639980-4bf4-11e9-9b63-5f2d6f93232a.png)

This image definitely exists in the container registry. The credentials for the registry did not change. A task is able to pull the image configured in the pool, which only has a different image tag.

1. Our images are based on Linux alpine, so we're ok with pull cost at run time.
From what I understood, I can create a pool without specifying container configuration, and have only the task to specify the image. I created a new pool with 1 dedicated node like this:

![image](https://user-images.githubusercontent.com/4509839/54766939-1c468d80-4bf4-11e9-87e0-6fe09a489ca8.png)

What is the difference between Container configuration: None and Container configuration: Custom without any registries / images?

2. Indeed I do provide the container registry in `TaskContainerSettings`:
```
private CloudTask ToCloudTask(TaskDefinition definition)
{
	var registry = CreateContainerConfig().ContainerRegistries.Single();
	return new CloudTask(definition.Id, definition.Command)
	{
		ResourceFiles = definition.BlobUris.Select(ToResourceFile).ToArray(),
		ContainerSettings = new TaskContainerSettings(_options.ModelTrainingImage, registry: registry)
	};
}
```

3. Using the node pool from point 1., I ran another job. It failed with:
```
Category: UserError
Code: ContainerPoolNotSupported
Message: The compute node does not support container feature
```

![image](https://user-images.githubusercontent.com/4509839/54767782-d5599780-4bf5-11e9-815b-ab037ae8eb5d.png)

**Comment by alfpark** [comment]
Thanks @xenalite for the information.

1. Container configuration of None means that the pool will not be container compliant - you won't be able to specify container tasks.
3. As far as I understand this error means that you didn't specify a container configuration, but clearly you have. This may be a portal issue.

I'll reach out to some of the experts on the team to see if they have any insight here.

cc @xingwu1, @timotheeguerin, @zfengms

**Comment by xingwu1** [comment]
@xenalite for the original issue, if the node is live, could you provide the account name, pool name, so I can look the log to see what caused this issue? Or you can file azure incident, there will be CSS person transfer the information to the dev.

**Comment by xingwu1** [comment]
@xenalite BTW, the pool container settings is accepted multiple image list. So it will download multiple container images when node start up.

**Comment by xenalite** [comment]
@alfpark I think you are correct about the portal issue. Compare pool created via the Portal vs Azure Batch SDK for .NET:

Created via Portal with Docker configuration: Custom
![image](https://user-images.githubusercontent.com/4509839/54789528-a7db1100-4c2a-11e9-9d77-116ceba99145.png)

Created via Azure Batch SDK for .NET:
![image](https://user-images.githubusercontent.com/4509839/54789595-e96bbc00-4c2a-11e9-9575-e17419b15c86.png)

Code to create the pool above:
```csharp
private async Task<PoolInformation> GetPoolInfo(BatchClient batchClient, int nodeCount)
{
    var imageReference = GetNodeImage();
    var nodeAgentSku = GetNodeAgentSku(batchClient, imageReference);

    var containerConfig = new ContainerConfiguration
    {
        ContainerRegistries = new List<ContainerRegistry>(),
        ContainerImageNames = new List<string>()
    };

    var vmConfig = new VirtualMachineConfiguration(imageReference, nodeAgentSku.Id)
    {
        ContainerConfiguration = containerConfig
    };

    var pool = batchClient.PoolOperations.CreatePool(
        $"test_{Guid.NewGuid()}", _options.NodeSize,
        vmConfig, nodeCount);

    await pool.CommitAsync();

    return new PoolInformation {PoolId = pool.Id};
}
```

The second pool, created via SDK, was able to run a task with task container settings despite not having any registries or images configured on the pool. I realize this is a separate issue to the original one - would you like me to raise another github issue for this?

**Comment by xenalite** [comment]
@xingwu1 I could raise a ticket with our Premier Support, but at this point I think I have a solution.
Up till now I was creating pools through the portal, subject to the issue in the above comment.
If I create my pools through the SDK as above, I can run multiple tasks with different container image versions, as you would expect. This solves my use case.

However, if you are still curious about what caused the original issue and cannot repro on your end, these are the details of the account and job to look at:

Batch account resource ID: `/subscriptions/a3f7b6af-0d5e-437c-b8cd-c2c4397740a3/resourceGroups/wtw-ixs-isolated-aml-aks/providers/Microsoft.Batch/batchAccounts/ixsamldem20ba01dev`
Pool Name: `ui_tests`
Job Name: `54e34aa2-67e3-4124-8a64-c5ce02f13b50`

Thank you both for your help.

**Comment by xingwu1** [comment]
@xenalite I noticed the portal error too, and our portal dev has followed up on this issue.

**Comment by xingwu1** [comment]
@xenalite could you provide the image name try to pull down? In the log, I can see we failed to pull download the image **ixsamldem20cr01dev.azure.io/wtw.aml.pythoncore:0.5.0-pullrequest4971.430_74850.**

Could you confirm this image name is correct?

**Comment by xenalite** [comment]
@xingwu1 Hello. I assuming we are taking about the same job (starting with `54e`):
The image name above is incorrect:
`ixsamldem20cr01dev.azure.io/wtw.aml.pythoncore:0.5.0-pullrequest4971.430_74850`

It should be:
`ixsamldem20cr01dev.azurecr.io/wtw.aml.pythoncore:0.5.0-pullrequest4971.430_74850`

This image exists:
```
PS C:\Users\oskar207> docker pull ixsamldem20cr01dev.azurecr.io/wtw.aml.pythoncore:0.5.0-pullrequest4971.430_74850
0.5.0-pullrequest4971.430_74850: Pulling from wtw.aml.pythoncore
f7e2b70d04ae: Already exists
(...)
```

Second image name (with **azurecr.io** instead of **azure.io**) is shown in the portal:
![image](https://user-images.githubusercontent.com/4509839/54808347-db905800-4c77-11e9-888f-533bc39e5e31.png)

**Comment by xingwu1** [comment]
It looks like our dependency had fixed this bug (https://github.com/docker/docker-py/commit/c53423f11851a69fa18783b5b0b801a24d8d2f82) , we will update our node agent to pick up newer version.

**Comment by alfpark** [comment]
@xenalite wrt the Portal issue creating a non-container compliant pool when the container configuration is not None has been identified and will be fixed soon.

**Comment by xenalite** [comment]
@alfpark @xingwu1 Hello. I found the root cause of our original problem with images not being found.

I have the repro steps (tested on 2 different static pools):

1. Create a new "static" pool of nodes with Docker configuration. Node size with small temp drive will reproduce issue faster (we used A1_v2 with 10 GB temp drive).

2. Do not de-allocate any nodes and run many container tasks over a week or so (we ran 130 tasks with container images of about 800 MB).

3. In the beginning the tasks will pull docker images just fine and save output files without an issue.

4. After a while, the temp drive will fill up, making Docker pulls impossible. Referencing new Docker image versions will fail with:
```
UserError ContainerInvalidImage
One or more container images specified are invalid
ContainerImage: ixsamldem20cr01dev.azurecr.io/wtw.aml.pythoncore:0.5.0-alpha.443_76566
Message: no such image: ixsamldem20cr01dev.azurecr.io/wtw.aml.pythoncore:0.5.0-alpha.443_76566: No such image: ixsamldem20cr01dev.azurecr.io/wtw.aml.pythoncore:0.5.0-alpha.443_76566
```

5. If you SSH into the machine, you will find that the temp drive mount `/mnt/resource` is 100% full.
```
[root@f7081200cd61406c9082c8a136e7474d000000 resource]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        30G  1.8G   28G   6% /
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G   25M  1.9G   2% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda1       497M   97M  401M  20% /boot
/dev/sdb1        16G   16G     0 100% /mnt/resource
tmpfs           394M     0  394M   0% /run/user/1001
[root@f7081200cd61406c9082c8a136e7474d000000 resource]# du -a . | sort -n -r | head -n 20
16092176        .
15254704        ./docker
15224804        ./docker/overlay2
837448  ./batch
669900  ./batch/tasks
669876  ./batch/tasks/workitems
462832  ./docker/overlay2/eed7938e62c4014221e20037a456505ef26a3f73926efe7151e67673de2052b0
462816  ./docker/overlay2/eed7938e62c4014221e20037a456505ef26a3f73926efe7151e67673de2052b0/diff
462808  ./docker/overlay2/eed7938e62c4014221e20037a456505ef26a3f73926efe7151e67673de2052b0/diff/usr
462804  ./docker/overlay2/eed7938e62c4014221e20037a456505ef26a3f73926efe7151e67673de2052b0/diff/usr/local
462804  ./docker/overlay2/83c36bb2f0bc2e1290964391773b5c17d3b1adb838775fe32f609f1d3854fae0
462788  ./docker/overlay2/83c36bb2f0bc2e1290964391773b5c17d3b1adb838775fe32f609f1d3854fae0/diff
462780  ./docker/overlay2/83c36bb2f0bc2e1290964391773b5c17d3b1adb838775fe32f609f1d3854fae0/diff/usr
462776  ./docker/overlay2/83c36bb2f0bc2e1290964391773b5c17d3b1adb838775fe32f609f1d3854fae0/diff/usr/local
462764  ./docker/overlay2/fcebf318c5e5b328564dea3a63addd87796b2ba6084ee61df3179b7f3ff30534
462764  ./docker/overlay2/f184aa56799ff9673b9b0548724fb57eacd0eaf8551816ccb949d55238f64f7f
462764  ./docker/overlay2/f0d49596e3b4d8233ed5997922e910728cb1155bf04804c7832a455cddd933db
462764  ./docker/overlay2/f0acb5c95563d91f05b739973686e5066d9b579e23af655746f6f9c1e87896e0
462764  ./docker/overlay2/dfdeb24455232439d4595ff16444bf5269e171122e2beefcb7f367c021806aab
462764  ./docker/overlay2/d8008f38a6001c71997929520f66ece992e2129d790d137a89167dec75acbe8f
```

6. If you attempt to run a container using an image that is already present, the task will succeed, but any output files saved into the working directory will be empty. This is how we discovered this problem. We have a container image that runs a bit of Python and produces an output file. The output file did not fail to save or throw exceptions. It's content was simply empty, failing our process elsewhere.

7. Interestingly, if a task has any input files to be downloaded from Azure Storage Account, it will manage to download them.

I believe there is a bug here around proper error messaging. Neither "image not found" nor successfully saving an empty file suggest a full disk.

**Comment by xenalite** [comment]
After scaling the pool to 0 then back to target count, I could pull images and produce output files again.

**Comment by alfpark** [comment]
Thanks @xenalite for the info, this is fantastic.

@xingwu1 can we look into improving the error messaging here? I know we have some limitations around what the client feeds back to us.

**Comment by xingwu1** [comment]
@xenalite Yes. The message is misleading though that is how docker service feed us. I will try to find the way to let our agent figure the root reason. BTW, I guess the finished container fill up tmp drive, not the image. One thing you can do is: add '--rm' to the containerRunOptions, so the finished container will be removed after task finished. The other way is change the Batch task retention time to smaller, for example: 1 day instead of default 7 days if you don't need hold the finished task information in the VM.

**Comment by xenalite** [comment]
@alfpark 
> @xenalite wrt the Portal issue creating a non-container compliant pool when the container configuration is not None has been identified and will be fixed soon.

I can confirm the Portal issue is resolved. I created a pool today through the Portal with Custom docker configuration with no registries or images and the pool is now showing as docker compatible.

**Comment by alfpark** [comment]
The login/pull logic and error capture messaging was improved in [1.5.6](https://github.com/Azure/Batch/blob/master/changelogs/nodeagent/CHANGELOG.md#156---2019-04-19).
