### ISSUE TITLE
Azure batch 10.1.0 task dependency not working

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/Batch#55]
`
taskA.ExitConditions = new ExitConditions() { Default = new ExitOptions() { DependencyAction = Microsoft.Azure.Batch.Common.DependencyAction.Satisfy } };

taskB.DependsOn = TaskDependencies.OnId(taskA.Id);
`

When taskA completed with error, taskB is not executed and remain on active state, I recall this code was working on the past, it was based on following example.

![image](https://user-images.githubusercontent.com/12871379/56790333-9924e280-6804-11e9-946f-6deace192e8c.png)

If there is strange thing, I got this message now "To enable exit conditions you need to set onTaskFailure on the job to to 'performexitoptionsjobaction'
![image](https://user-images.githubusercontent.com/12871379/56790382-bc4f9200-6804-11e9-8a38-e594fb4d52c0.png)

Previously this code is sufficient
`
job.UsesTaskDependencies = true;
`

It seems I need to update it into

```
job.UsesTaskDependencies = true;
job.OnTaskFailure = OnTaskFailure.PerformExitOptionsJobAction;
```

**Comment by andrew-vdb** [comment]
No, if I do job.OnTaskFailure = OnTaskFailure.PerformExitOptionsJobAction; It will cause the job to be terminated.

![image](https://user-images.githubusercontent.com/12871379/56793401-3df6ee00-680c-11e9-8ae9-3c77dc6ac40f.png)

**Comment by alfpark** [comment]
@andrew-vdb Can you confirm that your pool is using node agent version 1.5.5 or newer? A regression with task exit conditions was addressed in that version.

**Comment by theunrepentantgeek** [comment]
I just had a go at reproducing this behavior. I defined a simple job with two tasks, as follows:

* **Task A**: completes with exitCode 32 and has a match `ExitCodition` set so that this satisfies dependencies.

* **Task B**: depends on A

**Result:** Task A failed, but Task B ran as expected.

I didn't need to set `job.OnTaskFailure = OnTaskFailure.PerformExitOptionsJobAction`.

Here's the JSON export of my Task A (with some details elided to save space):

``` json
{
    "id": "A",
    "url": "https://bearpscy4.westcentralus.batch.azure.com/jobs/job1132/tasks/A",
    "exitConditions": {
        "exitCodes": [
            {
                "code": 32,
                "exitOptions": {
                    "dependencyAction": "satisfy"
                }
            }
        ]
    },
    "state": "completed",
    "stateTransitionTime": "2019-04-29T23:38:34.686Z",
    "commandLine": "cmd /c exit 32",
    "executionInfo": {
        "startTime": "2019-04-29T23:38:31.858Z",
        "endTime": "2019-04-29T23:38:34.686Z",
        "exitCode": 32,
        "failureInfo": {
            "category": "UserError",
            "code": "FailureExitCode",
            "message": "The task exited with an exit code representing a failure",
            "details": [
                {
                    "name": "Message",
                    "value": "The task exited with an exit code representing a failure"
                }
            ]
        },
        "retryCount": 0,
        "requeueCount": 0,
        "result": "failure"
    }
}
```

@andrew-vdb How does this compare with your task A?

**Comment by andrew-vdb** [comment]
@alfpark No, my version is 1.5.3
![image](https://user-images.githubusercontent.com/12871379/56945140-4dd14380-6b26-11e9-89d9-24e882f4ca79.png)

How to update node agent version? Seems it is something automatic.

@theunrepentantgeek looks like my node agent version is the problem....

**Comment by alfpark** [comment]
@andrew-vdb We are making improvements in this area to make this more automated. For now, please recreate your pool.

**Comment by andrew-vdb** [comment]
Thanks its working again.
