### ISSUE TITLE
Batch nodes are in unusable state when joined to a subnet with subnet-wide NSG applied.

### ISSUE THREAD

**Issue by xenalite** [Azure/Batch#67]
#### Problem Description
Batch nodes are in unusable state when joined to a subnet with subnet-wide NSG applied.

#### Steps to Reproduce

I am creating a Batch node pool joined to a subnet as described here:
https://docs.microsoft.com/en-us/azure/batch/batch-virtual-network#pools-in-the-virtual-machine-configuration

I can see Load Balancer, NSG and Public IP deployed in my resource group for the batch nodes.
My subnet has an extra NSG applied to it. It has the following rules in it:

![image](https://user-images.githubusercontent.com/4509839/60968499-22808700-a315-11e9-8728-cf9b7c0c48da.png)

This is as described in the documentation. Yet the nodes are in unusable state.

#### Expected Results
Nodes to be in usable state and servicing jobs.

#### Actual Results
Nodes are in unusable state. Job hangs.

#### Additonal Comments
- The nodes come back from unusable state to servicing jobs again if I change the outbound rule from Storage service tag only to Internet (on any port). 
- Setting AzureCloud service tag on any port doesn't work either.
- Why does Batch subnet's NSG need outbound traffic at all? The only resources I want my batch nodes to talk to is my storage account and my container registry. Both are accessible through Service Endpoints.

**Comment by alfpark** [comment]
@xenalite Sorry for the delay in response, can you please open a support request? We can try to figure out what is going on for the first two comments.

For the last comment, Batch compute nodes need to communicate with Azure Storage services to facilitate service-level functionality.

**Comment by xenalite** [comment]
@alfpark Thanks for the reply. Raised a ticket 119071625000587 if you are interested.

About last comment - just to confirm - Do I still need outbound Storage rule if my Batch account is not configured with a storage account? 
In our case, our data and workload comes from multiple storage accounts which we want to firewall and service endpoint to the subnets.

**Comment by alfpark** [comment]
Correct, you still need an outbound Storage rule.

**Comment by xenalite** [comment]
Thank you. Issue resolved. Required Storage and AzureContainerRegistry service tags outbound.
