### ISSUE TITLE
FileUploadMiscError

### ISSUE THREAD

**Issue by chaor11** [Azure/Batch#68]
I am trying to persist output data when a task is completed. The way I do it is use the 'output_files' parameter of the TaskAddParameter function. But I keep running into FileUploadMiscError. Specifically, below are my fileuploaderr.txt and fileuploadout.txt.

Why is the URI not valid? It seems that the file_pattern="../stdout.txt",  is a valid one. Could it be the naming problem of the destination 'container_url' or 'path' ?

{"code": "InternalError", "user_error": false, "pattern": "../stdout.txt", "file": "/mnt/batch/tasks/workitems/testjob/job-1/Task2/stdout.txt", "destination": "https://chaor11.blob.core.windows.net/testoutput?restype=container&sr=c&sig=quFEalQnU88BYdoNlPuXl3tQokc1HqaISmgmniiO1Gg%3D&sp=w&sv=2018-03-28&se=2019-08-30T01%3A15%3A21Z"}

2019-07-19 09:19:12,740 System default encoding=utf-8, filesystem encoding=utf-8, default locale encoding=UTF-8
2019-07-19 09:19:12,742 Resolved mappings: [[Resolved mapping - base_path: /mnt/batch/tasks/workitems/testjob/job-1/Task2, full_pattern: /mnt/batch/tasks/workitems/testjob/job-1/Task2/stdout.txt, original_pattern: ../stdout.txt,  destination: 1_11_0.txt]]
2019-07-19 09:19:12,747 Uploading all files matching pattern /mnt/batch/tasks/workitems/testjob/job-1/Task2/stdout.txt
Client-Request-ID=45b46a00-aa06-11e9-85f0-000d3a3206f7 Retry policy did not allow for a retry: Server-Timestamp=Fri, 19 Jul 2019 09:19:12 GMT, Server-Request-ID=7d8a8d00-101e-001f-5013-3e3f18000000, HTTP status code=400, Exception=The requested URI does not represent any resource on the server.<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.RequestId:7d8a8d00-101e-001f-5013-3e3f18000000Time:2019-07-19T09:19:12.7858957Z</Message></Error>.
Traceback (most recent call last):
  File "/source/src/batchfileuploader.py", line 106, in main
  File "/source/src/agent/fileupload/uploader.py", line 483, in run
  File "/source/src/agent/fileupload/uploader.py", line 404, in push_file_list_to_storage
common.exceptions.AggregateException: file: /mnt/batch/tasks/workitems/testjob/job-1/Task2/stdout.txt from pattern: ../stdout.txt to destination: https://chaor11.blob.core.windows.net/testoutput?restype=container&sr=c&sig=quFEalQnU88BYdoNlPuXl3tQokc1HqaISmgmniiO1Gg%3D&sp=w&sv=2018-03-28&se=2019-08-30T01%3A15%3A21Z hit error: Traceback (most recent call last):
  File "/source/src/common/util/fileupload.py", line 92, in upload_multiple_files
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 463, in create_blob_from_path
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 582, in create_blob_from_stream
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 1101, in _put_blob
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
  File "/source/out/buildenvs/ubuntu-18.04-venv/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
azure.common.AzureHttpError: The requested URI does not represent any resource on the server.
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:7d8a8d00-101e-001f-5013-3e3f18000000
Time:2019-07-19T09:19:12.7858957Z</Message></Error>

**Comment by chaor11** [comment]
I tried the following two ways to create url, but both failed.

(1) 
output_sas_url = "https://{}.blob.core.windows.new/{}?{}".format(config._STORAGE_ACCOUNT_NAME, config._OUTPUT_CONTAINER, output_sas_token)

(2)
output_sas_url = blob_service_client.make_container_url(
                        container_name=config._OUTPUT_CONTAINER,
                        sas_token=output_sas_token)

**Comment by chaor11** [comment]
Here is my code.

`def add_tasks(batch_service_client, blob_service_client, job_id):
    """
    Adds a task for each input file in the collection to the specified job.
    :param batch_service_client: A Batch service client.
    :type batch_service_client: `azure.batch.BatchServiceClient`
    :param blob_service_client: A Blob service client.
    :type blob_service_client: `azure.batch.BatchServiceClient`
    :param str job_id: The ID of the job to which to add the tasks.
    """

    # generate list of ResourceFile's for all blobs in 'src', required when creating every task
    resource_files = list()
    src_generator = blob_service_client.list_blobs(config._SRC_CONTAINER)
    
    for blob in src_generator:
        src_sas_token = blob_service_client.generate_blob_shared_access_signature(
            config._SRC_CONTAINER,
            blob.name,
            permission=azureblob.BlobPermissions.READ,
            expiry=datetime.datetime.utcnow() + datetime.timedelta(hours=1000))

        src_sas_url = blob_service_client.make_blob_url(config._SRC_CONTAINER,
                                                blob.name,
                                                sas_token=src_sas_token)

        resource_files.append(batchmodels.ResourceFile(http_url=src_sas_url, file_path=blob.name))
    
    input_generator = blob_service_client.list_blobs(config._INPUT_CONTAINER)
    print('Adding {} tasks to job [{}]...'.format(len(list(input_generator)), job_id))

    output_sas_token = blob_service_client.generate_container_shared_access_signature(
        container_name=config._OUTPUT_CONTAINER,
        permission=azureblob.BlobPermissions.WRITE,
        expiry=datetime.datetime.utcnow() + datetime.timedelta(hours=1000)
    )
    
    #output_sas_url = "https://{}.blob.core.windows.new/{}?{}".format(config._STORAGE_ACCOUNT_NAME, config._OUTPUT_CONTAINER, output_sas_token)
    output_sas_url = blob_service_client.make_container_url(
                        container_name=config._OUTPUT_CONTAINER,
                        sas_token=output_sas_token)

    for idx, blob in enumerate(input_generator):
        # generate the command for the task
        command = "/bin/bash -c \"./test < {}\"".format(blob.name)

        # generate ResourceFile for the input, required when creating task
        input_sas_token = blob_service_client.generate_blob_shared_access_signature(
            config._INPUT_CONTAINER,
            blob.name,
            permission=azureblob.BlobPermissions.READ,
            expiry=datetime.datetime.utcnow() + datetime.timedelta(hours=1000))

        input_sas_url = blob_service_client.make_blob_url(config._INPUT_CONTAINER,
                                                blob.name,
                                                sas_token=input_sas_token)
        
        batch_service_client.task.add(job_id, batch.models.TaskAddParameter(
                id="Task{}".format(idx),
                command_line=command,
                resource_files=resource_files+[batchmodels.ResourceFile(http_url=input_sas_url, file_path=blob.name)],
                output_files=[batchmodels.OutputFile(
                    file_pattern=blob.name,#"../stdout.txt", 
                    destination=batchmodels.OutputFileDestination(
                        container=batchmodels.OutputFileBlobContainerDestination(
                            #path="task{}.txt".format(idx),
                            container_url=output_sas_url)),
                    upload_options=batchmodels.OutputFileUploadOptions(
                        upload_condition=batchmodels.OutputFileUploadCondition.task_success))]
        )
        )`

**Comment by bgklein** [comment]
Hello thanks for submitting this.

First off you should not use the helper method due to this issue https://github.com/Azure/azure-storage-python/issues/543.

Could you also confirm that the container you are trying to upload to already exists? This is not done automatically and seems to be what your error message is indicating.

**Comment by chaor11** [comment]
I just replaced the expiry time of 1000hrs to 48hrs, and it seems to work...at least for now...

**Comment by chaor11** [comment]
> Hello thanks for submitting this.
> 
> First off you should not use the helper method due to this issue [Azure/azure-storage-python#543](https://github.com/Azure/azure-storage-python/issues/543). The manual way you specified should work though.
> 
> Could you also confirm that the container you are trying to upload to already exists? This is not done automatically and seems to be what your error message is indicating.

Thanks for the reference! I am pretty sure that my container already exists, and as I have said, I have tried both manually concatenation and the make_container_url function: they all failed. 

I changed 1000hrs to 48hrs, and it turned out to work, at least for now.
