### ISSUE TITLE
Integrate Batch with Log Analytics when deploying via an ARM template

### ISSUE THREAD

**Issue by jn-altius** [Azure/Batch#76]
#### Feature Request Description
I  have an ARM template with which I deploy Batch account via Azure DevOps.  The ARM template has a 'resources' section for Microsoft.Batch/batchAccounts, which contains a 'resources' section for 3 Microsoft.Batch/batchAccounts/pools
I have been using the template for a year with no problems.

Now I would like to enable Diagnostic settings for this Batch account, and send the logs to an existing Log Analytics Workspace in the same subscription, but in a different Resource Group.  I would like to do this in the same ARM template and not with separate PS or CLI files.

I can see an example for how to do this with Azure SQL:
https://github.com/Azure/azure-quickstart-templates/blob/master/201-sql-auditing-server-policy-to-oms/azuredeploy.json

But when I attempt this same operation with Azure Batch I receive the error message 
```
  "error": {
    "code": "PropertyCannotBeUpdated",
    "message": "A property that cannot be updated was specified as part of the request.\nRequestId:<redacted>\nTime:2019-12-03T15:25:24.5847963Z",
    "target": "BatchAccount",
    "details": [
      {
        "code": "Reason",
        "message": "A property that cannot be updated was specified as part of the request."
      },
      {
        "code": "PropertyName",
        "message": "deploymentConfiguration"
      },
      {
        "code": "PropertyPath",
        "message": "properties.deploymentConfiguration"
      }
    ]
  }
```

This implies that Diagnostic settings cannot be set using ARM templates :-|  Also I noticed that even when I set up Diagnostic settings via the portal and export the ARM template, there is no mention of these settings.

#### Describe Preferred Solution
If the above error message is correct and Diagnostic settings cannot be set with ARM templates, please could this feature be added?

If the above error is a misnomer and actually Diagnostic settings _can_ be set with ARM templates, please could an example be published?  Even better, could that example use a Log Analytics Workspace, in a different Resource Group to the Batch account?

**Comment by alfpark** [comment]
Tagging @jafreck to possibly help here.

**Comment by alfpark** [comment]
This is supported under preview via pool VM extensions, but requires your account to be enabled for this prior to this feature being GA. You can raise a support ticket to allow this feature. Please see: https://docs.microsoft.com/azure/batch/create-pool-extensions
