### ISSUE TITLE
Windows Data Science VM image is outdated

### ISSUE THREAD

**Issue by letmaik** [Azure/Batch#8]
The Azure Batch image "microsoft-ads:standard-data-science-vm:standard-data-science-vm" looks like an outdated version of the normal Windows 2016 variant. It runs on Windows Server 2012 and has differences like described on https://feedback.azure.com/forums/910651-data-science-vm/suggestions/34849414-make-python-3-the-default. How do I know which version of the regular DSVM this Batch variant corresponds to and how often is the latter updated?

**Comment by alfpark** [comment]
Azure Batch Marketplace images are exactly the same ones that correspond for "normal" VM and VMSS resources.

An update to a newer version of the DSVM on WS2016 is forthcoming.

**Comment by alfpark** [comment]
Support for this was rolled out a while back.
