### ISSUE TITLE
Batch Service Infrastructure Upgrade Guidance

### ISSUE THREAD

**Issue by alfpark** [Azure/Batch#82]
## Guidance

Beginning 23 March 2020 at 00:00 UTC maintenance operations will modify the Batch service allocated IP addresses. During this service maintenance period, select operations may not complete successfully. 

### Recommended action

To ensure that you experience minimal to no interruption during this period:

1.	Ensure that the "BatchNodeManagement" service tag (or regional variant) is utilized for any applicable network resource linked to a Batch pool, such as network security groups (NSGs).
2.	Applicable network resources linked to a Batch pool that cannot utilize service tags, such as [user defined routes (UDRs)](https://docs.microsoft.com/azure/batch/batch-virtual-network#user-defined-routes-for-forced-tunneling) and classic virtual network ACLs must reflect the proper backing IP addresses used in the "BatchNodeManagement" service tag (or regional variant). Please see the [list of Azure Public Cloud IP addresses](https://www.microsoft.com/download/details.aspx?id=56519) used by the "BatchNodeManagement" service tag and regional variants. Please see the addendum section below for other Azure Cloud region IP addresses.
3.	Ensure that your systems are honoring DNS Time-to-Live (TTL) for your Batch account service URL. Additionally, ensure that your Batch service clients and other connectivity mechanisms to the Batch service do not rely on IP addresses.
4.	Ensure that your Batch service clients have appropriate retry policies in place to automatically retry your requests, even during normal operation and not exclusively during service maintenance. These retry policies should span an interval of at least 5 minutes. Automatic retry capabilities are provided with various Batch SDKs, such as the [.NET RetryPolicyProvider class](https://docs.microsoft.com/dotnet/api/microsoft.azure.batch.retrypolicyprovider?view=azure-dotnet).
5.	If your requests continue to receive 5xx level HTTP responses, your Batch service clients should observe the "Connection: close" header, re-resolve DNS for the Batch account service URL, and attempt following requests on a new connection.

### Addendum

1. For US Government Cloud IP addresses used in the "BatchNodeManagement" service tag, please [download this list](https://www.microsoft.com/download/details.aspx?id=57063).
2. For China Cloud IP addresses used in the "BatchNodeManagement" service tag, please [download this list](https://www.microsoft.com/download/details.aspx?id=57062).

## Batch Service Upgrade Timelines

**Update 30 April 2020:** Timelines for upgrade no longer need to be shared due to improvements in the planned upgrade process. Please see [this comment](https://github.com/Azure/Batch/issues/82#issuecomment-622204474) for more information.

**Update 20 March 2020:** Migration start time has been delayed. Please note that regardless of the migration start time for any particular region, verifying your configuration with Azure Batch as per recommended actions above will ensure your readiness. Please keep checking back on this issue for new timeline updates.

**Comment by gourgopal** [comment]
Thanks for the Recommended Action, @alfpark 
I have few questions:
1. Does it have any effect on BatchService that runs using Azure Management/Fluent .NET Libraries? 
2. Does it have any effect if we are using Virtual Network to connect to Storage Container ?
3. In Point No. 3 regarding the DNS TTL - What changes are needed to make for the BatchService using the .NET Libraries or need to make any external changes are needed?
4. We haven't used 'BatchNodeManagement' - Do we need to use them after the Infrastructure Upgrade ?

**Comment by chrisalexander** [comment]
@alfpark Please could you add a comment when updating timelines etc. (anything important in the original issue text) otherwise Github doesn't necessarily send a notification, even to subscribers to the issue. Thank you!

**Comment by alfpark** [comment]
Please refer to our documentation for best practices with respect to this issue. 

- [Connectivity to the Batch Service](https://docs.microsoft.com/azure/batch/best-practices#connectivity-to-the-batch-service)
- [Network Security Groups](https://docs.microsoft.com/azure/batch/batch-virtual-network#network-security-groups-batch-default): please pay particular attention to the `Warning` box and follow guidance
- [User-defined Routes](https://docs.microsoft.com/azure/batch/batch-virtual-network#user-defined-routes-for-forced-tunneling): please pay particular attention to the `Warning` box and follow guidance

Customers applying these best practices should observe no interruption in their workload during our forthcoming infrastructure upgrade. As such, customers following these best practices in combination with improvements in our service to better handle this infrastructure upgrade, there is no longer a need for upgrade timelines to be shared.
