### ISSUE TITLE
nothing is geting writte to stdout and stderr file in job task

### ISSUE THREAD

**Issue by qudiransari** [Azure/Batch#84]
#### Problem Description
After running the batch,its showing completed successfully but nothing is getting written to stdout or stderr file when i checked my job->task file. My code is geting executed but with no result so i guess some error is happeing which is not caught inside my try catch .
Do i need to write explicitly or as i know the error is automatically written to the stderr file.

#### Steps to Reproduce
execute batch using python script

I have included the below syntax as well:
from __future__ import print_function
import sys
print("Custom message from runtime documentparser", file=sys.stderr)

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
Please see this [StackOverflow Question](https://stackoverflow.com/questions/56781405/how-to-update-stdout-txt-during-task-execution-real-time/56782059#56782059).
