### ISSUE TITLE
Using ARM Template to deploy batchpools utilising "bring your own public ips" doesn't appear to be idempotent

### ISSUE THREAD

**Issue by strichar** [Azure/Batch#85]
#### Problem Description
When deploying an Azure Batch pool using the documented ARM reference template:
https://docs.microsoft.com/en-us/azure/templates/microsoft.batch/2019-08-01/batchaccounts/pools
and specifying the resource ID of the public ip addresses you bring at:
"publicIPs": [
        "string"
      ]

The first deployment is successful

The second deployment (with no parameters changed) fails with:
message": "{\r\n  \"error\": {\r\n    \"code\": \"PropertyCannotBeUpdated\",\r\n    \"message\": \"A property that cannot be updated was specified as part of the
request.\\nRequestId:4c012976-fa1f-4a58-beed-3e47dd507546\\nTime:2020-05-07T10:17:24.4566932Z\",\r\n    \"target\": \"BatchAccount\",\r\n    \"details\": [\r\n      {\r\n        \"code\":
\"Reason\",\r\n        \"message\": \"A property that cannot be updated was specified as part of the request.\"\r\n      },\r\n      {\r\n        \"code\": \"PropertyName\",\r\n        \"message\": 
\"networkConfiguration\"\r\n      },\r\n      {\r\n        \"code\": \"PropertyPath\",\r\n        \"message\": \"properties.networkConfiguration\"\r\n      }\r\n    ]\r\n  }\r\n}"

The actual ARM representation that is set (if you do a get against resource) is in a different format:
"publicIPAddressConfiguration": {
        "ipAddressIds": [
          "/subscriptions/c2593bfb-ef25-45e2-93bd-af1ce6203bb4/resourceGroups/azurebatch-publicip/providers/Microsoft.Network/publicIPAddresses/azurebatchhpcgbbbatchpoolx0"
        ]
      },

Redeploying the ARM template using this JSON format is successful, but only if the batchpool is currently created.  It does not work creating new deployments.

#### Steps to Reproduce

Update attached template (rename from txt to json) to your environment and then deploy ie:
new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupName azurebatch `
-TemplateFile "c:\templates\batchpool.json"

DeploymentName          : 20-05-07-11-46-57  
ResourceGroupName       : azurebatch
ProvisioningState       : Succeeded
Timestamp               : 07/05/2020 11:13:03
Mode                    : Incremental        
TemplateLink            :
Parameters              :
Outputs                 :
DeploymentDebugLogLevel :

Then redeploy (without any changes, to prove idempotency):

new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupName azurebatch `
-TemplateFile "c:\templates\batchpool.json"

new-azresourcegroupdeployment : 12:14:41 - Resource Microsoft.Batch/batchAccounts/pools 'azurebatchhpcgbb/mypool' failed with message '{
  "error": {
    "code": "PropertyCannotBeUpdated",
    "message": "A property that cannot be updated was specified as part of the request.\nRequestId:73432ed7-404f-4941-aeab-6b016c30e84e\nTime:2020-05-07T11:14:37.8126538Z",
    "target": "BatchAccount",
    "details": [
      {
        "code": "Reason",
        "message": "A property that cannot be updated was specified as part of the request."
      },
      {
        "code": "PropertyName",
        "message": "networkConfiguration"
      },
      {
        "code": "PropertyPath",
        "message": "properties.networkConfiguration"
      }
    ]
  }
}'
At line:1 char:1
+ new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

new-azresourcegroupdeployment : 12:14:41 - A property that cannot be updated was specified as part of the request.
At line:1 char:1
+ new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 
new-azresourcegroupdeployment : 12:14:41 - networkConfiguration
At line:1 char:1
+ new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 
new-azresourcegroupdeployment : 12:14:41 - properties.networkConfiguration
At line:1 char:1
+ new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 
new-azresourcegroupdeployment : 12:14:41 - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see 
https://aka.ms/DeployOperations for usage details.
At line:1 char:1
+ new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

new-azresourcegroupdeployment : 12:14:41 - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see 
https://aka.ms/DeployOperations for usage details.
At line:1 char:1
+ new-azresourcegroupdeployment -name $deploymentName  -ResourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 

DeploymentName          : 20-05-07-11-46-57
ResourceGroupName       : azurebatch
ProvisioningState       : Failed
Timestamp               : 07/05/2020 11:14:37
Mode                    : Incremental
TemplateLink            :
Parameters              : 
Outputs                 :
DeploymentDebugLogLevel :

#### Expected Results
A second deployment with the same values would succeed

#### Actual Results
The second deployment fails
#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

#### Additonal Comments
This limits infrastructure as code opportunities as we can't use ARM templates to create / update / scale batch pool.  And goes against the guiding principles of ARM:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/overview
Repeatable results: Repeatedly deploy your infrastructure throughout the development lifecycle and have confidence your resources are deployed in a consistent manner. Templates are idempotent, which means you can deploy the same template many times and get the same resource types in the same state. You can develop one template that represents the desired state, rather than developing lots of separate templates to represent updates._

[batchpoolgit.txt](https://github.com/Azure/Batch/files/4592596/batchpoolgit.txt)

**Comment by alfpark** [comment]
It appears that you are attempting to update the pool with properties that cannot be updated.

```
"error": {
"code": "PropertyCannotBeUpdated",
"message": "A property that cannot be updated was specified as part of the request.\nRequestId:73432ed7-404f-4941-aeab-6b016c30e84e\nTime:2020-05-07T11:14:37.8126538Z",
"target": "BatchAccount",
"details": [
{
"code": "Reason",
"message": "A property that cannot be updated was specified as part of the request."
},
{
"code": "PropertyName",
"message": "networkConfiguration"
},
{
"code": "PropertyPath",
"message": "properties.networkConfiguration"
}
```

Are you certain that the pool was deleted fully and the public IPs were no longer used before attempting the create again?

**Comment by stack247** [comment]
Is there any resolution to the closing of this issue?
We just ran in to in to similar issue. The property it's complaining is `deploymentConfiguration`. Just 10 months ago, this works. I wonder if there's any change in Azure Batch?

Exception details:

```json
{
  "error": {
    "code": "PropertyCannotBeUpdated",
    "message": "A property that cannot be updated was specified as part of the request. RequestId:c13eccf4-1a8a-486c-9a23-b2c676eaf5df17 Time:2023-02-22T20:20:13.05471593Z",
    "target": "BatchAccount",
    "details": [
      {
        "code": "Reason",
        "message": "A property that cannot be updated was specified as part of the request."
      },
      {
        "code": "PropertyName",
        "message": "deploymentConfiguration"
      },
      {
        "code": "PropertyPath",
        "message": "properties.deploymentConfiguration"
      }
    ]
  }
}
```

**Comment by skrypnyk-dmytro** [comment]
> The property it's complaining is `deploymentConfiguration`

Hi @stack247! Did you find out what is wrong with it?
Cause I got the same problem on the template that worked one month before

**Comment by stack247** [comment]
> > The property it's complaining is `deploymentConfiguration`
> 
> Hi @stack247! Did you find out what is wrong with it? Cause I got the same problem on the template that worked one month before

No, I didn't find out what's wrong.
The way I made it work is by deleting the existing Pools and redeplying the ARM.

However, it'd be nice if we don't have to delete the existing Pools on every deployment.

**Comment by skrypnyk-dmytro** [comment]
Hi @stack247 . It was #153 issue. Already fixed
