### ISSUE TITLE
A8-A11 retirement and migration plans 

### ISSUE THREAD

**Issue by pkshultz** [Azure/Batch#87]
As we continue to bring more modern and optimized virtual machine instances to Azure, on the latest innovations in datacenter hardware, so too must we thoughtfully plan how we retire aging hardware. With this in mind, we are retiring our A8 – A11 Azure Virtual Machine sizes on 1 March 2021. This is a change from our previous announcement of an October 2020 retirement date. 

## How does this affect me? 

After 1 March 2021, any Batch pools with A8 – A11 Virtual Machines will become unusable. These Batch pools will not continue to be billed in their unusable state. 

## What actions should I take? 

Before 1 March 2021, you’ll need to delete your Batch pools with A8 – A11 Virtual Machines. We recommend moving your high-performance computing (HPC) workloads to another HPC Virtual Machine size. Learn more about choosing a Virtual Machine size for your Batch pools [here](https://docs.microsoft.com/azure/batch/batch-pool-vm-sizes).

We'll share more details about migration options in this GitHub issue.

**Comment by MinaPiao** [comment]
Hi Team, Customer noted that but  it will corrupt the cluster which hosts the app built on service fabric.  customer would like to have some more time frame and get the extension by 15th April, so they can plan the environment vm resize activity. Would you please let us know how to extend the timeframe ? Thanks.
