### ISSUE TITLE
Re-create pool due a change in "Managed Service"

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/Batch#88]
Incident on 07-06-2020, where you guys make an update and crashing all my azure batch environment. After a long discussion with Microsoft Support, we conclude on "Managed Service" is the problem, where I need to keep **pool** fresh by always re-create it for every month.

Question:
- Is this one time incident only? Due a change from **c++ pool manager** to **c# pool manager**
- If yes, then i will re-create the pool and forget this issue
- If no, then you need to exposed that information to azure portal

Keep in mind I'm talking about **pool managed service** and not "node agent version"

**Comment by alfpark** [comment]
Unfortunately support provided internal service details that are confusing.

Please consult the [best practices document](https://docs.microsoft.com/azure/batch/best-practices) regarding pool lifetime.
