### ISSUE TITLE
No Public IP for Batch Service in user subscription mode

### ISSUE THREAD

**Issue by Thialala** [Azure/Batch#90]
#### Feature Request Description
I have a Batch Service in **user subscription mode**. In our subscription, there is a policy denying the creation of a public IP. So, whenever I try yo create a pool via Batch Explorer, it fails. I'm using **user subscription mode** as the tasks need to access on-premises resources and azure resources protected by service Endpoint. 

I also tried to use the .NET Batch SDK and when I specify [NoPublicIPAddresses ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.common.ipaddressprovisioningtype?view=azure-dotnet) on NetworkConfiguration, I get a bad request: **Microsoft.Azure.Batch.Common.BatchException**: 'Operation returned an invalid status code 'BadRequest''
 
I'm using the code below:

```csharp
  private static async Task CreatePoolIfNotExist(BatchClient batchClient, string poolId, ResourceFile binariesZipFile = null)
        {
            var pools = await batchClient.PoolOperations.ListPools().ToListAsync();
            var alreadyExists = pools.Any(p => p.Id.Equals(poolId));

            if (alreadyExists)
            {
                Console.WriteLine($"Pool with id {poolId} already exists");
                return;
            }

            var pool = batchClient.PoolOperations.CreatePool(
                poolId: poolId,
                targetDedicatedComputeNodes: 1,
                virtualMachineSize: "Standard_D2s_v3",
                virtualMachineConfiguration: new VirtualMachineConfiguration(
                    new ImageReference("WindowsServer", "MicrosoftWindowsServer", "2019-Datacenter"),
                    "batch.node.windows amd64"));

            pool.ApplicationPackageReferences = new List<ApplicationPackageReference>
            {
                new ApplicationPackageReference {
                    ApplicationId = ApplicationId,
                    Version = Version
                }
            };

            pool.StartTask = CreateStartTask(binariesZipFile);

            pool.NetworkConfiguration = new NetworkConfiguration
            {
                SubnetId = SubnetId,
                PublicIPAddressConfiguration = new PublicIPAddressConfiguration(IPAddressProvisioningType.NoPublicIPAddresses)
            };

            await pool.CommitAsync();
        }
```

#### Describe Preferred Solution
It would be great to be able to create a pool without a public IP with only an internal load balancer.

Thanks !

**Comment by alfpark** [comment]
Can you provide more details on the error? This feature is not currently GA (generally available).

**Comment by Thialala** [comment]
Here is the full error:
_FeatureDisabled: Feature is disabled RequestId:<guid> Time:2020-06-23T07:25:53.5595434Z

Reason: Property provision is not enabled for current account
PropertyPath: properties.networkConfiguration.publicIPAddressConfiguration.provision_

When will the feature be available on West Europe ? Or is it possible to follow the release progress of this feature ?

Thanks!

**Comment by alfpark** [comment]
This is available in West Europe.
