### ISSUE TITLE
Default application version is displayed correctly but not using that package

### ISSUE THREAD

**Issue by josh-endries** [Azure/Batch#95]
I am currently having an issue where the default application version that I set via the API, and which shows up correctly in the Azure Portal, is not the version that is being used for new tasks when the version number is not included in the task definition. I've tried re-uploading the same application with another name/version and setting the default again via the API, but that didn't help. Setting it via the portal manually did seem to work, so it seems like there is a difference between the API and portal, however when I rolled out this new version in another Batch account, using the same deployment script, it did work...

The only other difference I've found is that another account I have which did work successfully via the API call currently has a notification about scaling to 0 and recreating the pool to use a newer node agent, whereas the pool where setting the default app version via the API didn't work doesn't have that notification.

**Comment by carogonzalezzapata** [comment]
Hey Josh, can you help us with the repro-steps, please?

**Comment by alfpark** [comment]
Closing stale issue, please comment to re-open if needed.
